#**Nominatim Geo Location Coding**

In [ ]:
from geopy.geocoders import Nominatim
import geopy.distance

In [ ]:
locator = Nominatim(user_agent="muskan")
location1 = locator.geocode("kollam")
location2 = locator.geocode("porbandar")
print("Latitude = {}, Longitude = {}".format(location1.latitude, location1.longitude))
l1 = (location1.latitude, location1.longitude)
l2 = (location2.latitude, location2.longitude)
geopy.distance.distance(l1, l2).km

Latitude = 8.8879509, Longitude = 76.5955013

1597.3191920755087

In [ ]:
print("Latitude = {}, Longitude = {}".format(location.latitude, location.longitude))

Latitude = 28.6138954, Longitude = 77.2090057

In [ ]:
location.raw, location.point, location.longitude, location.latitude, location.altitude, location.address

({'boundingbox': ['12.9914269', '12.9915269', '80.2336286', '80.2337286'],
  'class': 'amenity',
  'display_name': 'IIT Madras, Adayar, CMWSSB Division 174, Ward 174, Zone 13 Adyar, Chennai, Chennai District, Tamil Nadu, 600036, India',
  'icon': 'https://nominatim.openstreetmap.org/ui/mapicons/education_university.p.20.png',
  'importance': 0.6647465975709506,
  'lat': '12.9914769',
  'licence': 'Data © OpenStreetMap contributors, ODbL 1.0. https://osm.org/copyright',
  'lon': '80.2336786',
  'osm_id': 4727968819,
  'osm_type': 'node',
  'place_id': 53759422,
  'type': 'university'},
 Point(12.9914769, 80.2336786, 0.0),
 80.2336786,
 12.9914769,
 0.0,
 'IIT Madras, Adayar, CMWSSB Division 174, Ward 174, Zone 13 Adyar, Chennai, Chennai District, Tamil Nadu, 600036, India')

# **Wikipedia WK**

In [ ]:
!pip install wikipedia
import wikipedia as wk

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Collecting wikipedia
  Downloading wikipedia-1.4.0.tar.gz (27 kB)
Requirement already satisfied: beautifulsoup4 in /usr/local/lib/python3.7/dist-packages (from wikipedia) (4.6.3)
Requirement already satisfied: requests<3.0.0,>=2.0.0 in /usr/local/lib/python3.7/dist-packages (from wikipedia) (2.23.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.7/dist-packages (from requests<3.0.0,>=2.0.0->wikipedia) (2022.5.18.1)
Requirement already satisfied: chardet<4,>=3.0.2 in /usr/local/lib/python3.7/dist-packages (from requests<3.0.0,>=2.0.0->wikipedia) (3.0.4)
Requirement already satisfied: idna<3,>=2.5 in /usr/local/lib/python3.7/dist-packages (from requests<3.0.0,>=2.0.0->wikipedia) (2.10)
Requirement already satisfied: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in /usr/local/lib/python3.7/dist-packages (from requests<3.0.0,>=2.0.0->wikipedia) (1.24.3)
Building wheels for collected packages: wikipedia
  Building wheel for wikipedia (setup.py) ... done
  Created wheel for wikipedia: filename=wikipedia-1.4.0-py3-none-any.whl size=11695 sha256=429b10da9c7f5e8a09cc337a58ccc9936592a543c8353c0e6fa72b53c94565c2
  Stored in directory: /root/.cache/pip/wheels/15/93/6d/5b2c68b8a64c7a7a04947b4ed6d89fb557dcc6bc27d1d7f3ba
Successfully built wikipedia
Installing collected packages: wikipedia
Successfully installed wikipedia-1.4.0

In [ ]:
print(wk.search("IIT Madras"))

['IIT Madras', 'Indian Institutes of Technology', 'Joint Entrance Examination – Advanced', 'Inter IIT Sports Meet', 'IIT Tirupati', 'List of IIT Madras people', 'IIT Palakkad', 'History of Indian Institutes of Technology', 'Chennai', 'IIT Kharagpur']

In [ ]:
print(wk.search("IIT Madras", results=2))

['IIT Madras', 'Indian Institutes of Technology']

In [ ]:
print(wk.summary("IIT Madras"))

Indian Institute of Technology Madras (IIT Madras) is a public technical university located in Chennai, Tamil Nadu, India. As one of the Indian Institutes of Technology (IITs), it is recognized as an Institute of National Importance and has been consistently rated as one of India's most prestigious universities. Founded in 1959 with technical and financial assistance from the former government of West Germany, it was the third IIT established by the Government of India. IIT Madras is ranked the top engineering institute in India by the Ministry of Education's National Institutional Ranking Framework since its inception in 2016.IIT Madras is a residential institute that occupies a 2.5-square-kilometre (0.97 sq mi) campus that was formerly part of the adjoining Guindy National Park. The institute has nearly 600 faculty, 10,000 students and 1,250 administrative and supporting staff. Growing ever since it obtained its charter from the Indian Parliament in 1961, much of the campus is a protected forest, carved out of the Guindy National Park, home to large numbers of chital (spotted deer), black buck, bonnet macaque, and other rare wildlife. A natural lake, deepened in 1988 and 2003, drains most of its rainwater.

In [ ]:
print(wk.summary("IIT Madras", sentences=2))

Indian Institute of Technology Madras (IIT Madras) is a public technical university located in Chennai, Tamil Nadu, India. As one of the Indian Institutes of Technology (IITs), it is recognized as an Institute of National Importance and has been consistently rated as one of India's most prestigious universities.

In [ ]:
full_page = wk.page("IIT Madras")
full_page.content

'Indian Institute of Technology Madras (IIT Madras) is a public technical university located in Chennai, Tamil Nadu, India. As one of the Indian Institutes of Technology (IITs), it is recognized as an Institute of National Importance and has been consistently rated as one of India\'s most prestigious universities. Founded in 1959 with technical and financial assistance from the former government of West Germany, it was the third IIT established by the Government of India. IIT Madras is ranked the top engineering institute in India by the Ministry of Education\'s National Institutional Ranking Framework since its inception in 2016.IIT Madras is a residential institute that occupies a 2.5-square-kilometre (0.97 sq mi) campus that was formerly part of the adjoining Guindy National Park. The institute has nearly 600 faculty, 10,000 students and 1,250 administrative and supporting staff. Growing ever since it obtained its charter from the Indian Parliament in 1961, much of the campus is a protected forest, carved out of the Guindy National Park, home to large numbers of chital (spotted deer), black buck, bonnet macaque, and other rare wildlife. A natural lake, deepened in 1988 and 2003, drains most of its rainwater.\n\n\n== History ==\n\nIn 1956, the West German Government offered technical assistance for establishing an institute of higher education in engineering in India. The first Indo-German agreement was signed in Bonn, West Germany in 1959 for the establishment of the Indian Institute of Technology at Madras. IIT Madras was started with technical, academic and financial assistance from the Government of West Germany and was at the time the largest international educational project sponsored by the West German government. The Government of the Federal Republic of Germany has agreed to provide the following assistance in the establishment of a higher technological institute at Madras:\n\nA workshop, laboratory equipment, and a library whose total value does not exceed ₹1.8 crore (US$240,000).\nTwenty German professors to serve at the Institute for a period of four to five years\nFour German foremen for the workshops of the Institute for 2 years\nFacilities for the training of twenty Indian teachers in German institutionsThis has led to several collaborative research efforts with universities and institutions in Germany over the years. Although official support from the German government has ended, several research efforts involving the DAAD programme and Humboldt Fellowships still exist.\nThe Higher Technological Institute at Madras known as the Indian Institute of Technology, Madras has started functioning The first batch of 120 students was admitted in July 1959 to the first year of the Engineering Course. The institute was inaugurated in 1959, by the then Union Minister for Scientific Research and Cultural Affairs. The first batch had an overall strength of 120 students from across India. In 1961, the IITs were declared to be Institutes of National Importance. The first convocation ceremony was held on 11 July 1964, with Dr. S. Radhakrishnan, then the President of India, delivering the convocation address and awarding the degrees to the inaugural batch of students. The institute got its first women students in the BTech batch of 1966. IIT Madras celebrated its Golden Jubilee in 2009, and its Diamond Jubilee in 2019.\n\n\n== Campus ==\nThe main entrance of IIT Madras is on Sardar Patel Road, flanked by the residential districts of Adyar and Velachery. The campus is close to the Raj Bhavan, the official seat of the Governor of Tamil Nadu. Other entrances are located in Velachery (near Anna Garden MTC bus stop, Velachery Main Road), Gandhi Road and Taramani gate (close to Ascendas Tech Park).\nThe campus is located 10 km (6.2 mi) from the Chennai Airport, 12 km (7.5 mi) from the Chennai Central Railway station, and is connected by city buses. Kasturba Nagar is the nearest station on the Chennai MRTS line.\nTwo parallel roads, Bonn Avenue and Delhi Avenue, cut through the faculty residential area before they meet at the Gajendra Circle, near the Administrative Block. Buses regularly ply between the Main Gate, Gajendra Circle, the Academic Zone, and the Hostel Zone.\n\n\n=== Student Hostels ===\nMost students at IIT Madras reside in hostels, where extracurricular activities complement the academic routine. The campus has 20 hostels, of which four, Sharavati, Sarayu, Sabarmati and the recently constructed Tunga are exclusively for women. In earlier times, each hostel had attached dining facilities but all of them have since been closed down. Dining facilities are provided in three centralised halls: Nilgiri, Vindhya and Himalaya. Students are assigned to hostels upon matriculation, where they usually reside for the entire duration of their course of study.\n\nThe halls of IITM are:\n\nSindhu, Pampa, Mahanadhi and Tamiraparani are seven-storeyed whereas all the other hostels are three or four storeyed. These four hostels can accommodate more than 1,200 students. The older hostels were all three-storeyed till the early 2000s when extra rooms were added. An additional new floor in the three-storeyed hostels which generally house the undergraduate students and a new block in place of the mess halls of these hostels have been constructed to accommodate for the increased intake of the students. These new blocks could be used as entrances for these hostels. As of 2020, Mandakini has been demolished and a multi-storey block is under construction, with provision to accommodate approximately 1000 students.\n\n\n=== Facilities ===\nIIT Madras provides residential accommodation for its students, faculty, administrative and supporting staff, and their families. The residential houses employ private caterers. The self-contained campus includes two schools               (Vanavani and Kendriya Vidyalaya), three temples (Jalakanteshwara, Durga Peliamman and Ganapathi), three bank branches (SBI, ICICI, Canara Bank), a hospital, shopping centres, food shops, a gym, sleeping room and cricket, football, hockey and badminton stadiums. Internet is available in the academic zone and the faculty and staff residential zone. Earlier Internet was limited in hostel-zone from 2:00 pm till midnight and from 5:00 am to 8:00 am, but increasing demand during academic semester led to round-the-clock Internet service.IIT Madras also has supercomputing capability, with the IBM Virgo Super Cluster with 97 teraflops worth of computational power.\n\n\n== Organisation and administration ==\n\n\n=== Governance ===\nIIT Madras is an autonomous statutory organisation functioning within the Institutes of Technology Act. The sixteen IITs are administered centrally by the IIT Council, an apex body established by the Government of India. The Minister of Human Resources and Development is the chairman of the council. Each institute has a Board of Governors responsible for its administration and control.\nThe Senate comprises all professors of the Institute and decides its academic policy. It controls and approves the curriculum, courses, examinations, and results. It appoints committees to examine specific academic matters. The Director of the institute serves as the Chairman of the Senate. The current director is Kamakoti Veezhinathan.Three Senate Sub-Committees – The Board of Academic Research, The Board of Academic Courses and The Board of Students – help in academic administration and in the operations of the institute. The Finance Committee advises on matters of financial policy, while the Building and Works Committee advises on buildings and infrastructure. The Board of Industrial Consultancy and Sponsored Research addresses industrial consultancy and the Library Advisory Committee oversees library matters.\n\n\n=== Departments ===\nAerospace Engineering\nApplied Mechanics\nBiotechnology (Bhupat and Jyoti Mehta School of Biosciences)\nChemical Engineering\nChemistry\nCivil Engineering\nComputer Science and Engineering\nElectrical Engineering\nEngineering Design\nHumanities and Social Sciences\nMechanical Engineering\nManagement Studies\nMetallurgical and Materials Engineering\nMathematics\nOcean Engineering\nPhysics\n\n\n== Academics ==\nIIT Madras offers undergraduate, postgraduate and research degrees across 16 disciplines in Engineering, Sciences, Humanities and Management. About 360 faculty belonging to science and engineering departments and centres of the Institute are engaged in teaching, research and industrial consultancy.\nThe institute has 16 academic departments and advanced research centres across disciplines of engineering and pure sciences, with nearly 100 laboratories. The academic calendar is organised around the semester. Each semester provides a minimum of seventy days of instruction in English. Students are evaluated on a continuous basis throughout the semester. Evaluation is done by the faculty, a consequence of the autonomous status granted to the institute. Research work is evaluated on the basis of the review thesis by peer examiners both from within the country and abroad. Ordinances that govern the academic programme of study are prepared by the Senate, the highest academic body within the institute.\n\n\n=== Admission tests ===\nFor the undergraduate curriculum, admission to the BTech and Dual Degree (BSc + MSc or BTech + MTech) programme is done through the Joint Entrance Examination – Advanced (JEE-Advanced). IIT Madras conducted JEE Advanced in 2017. Admission to the five-year integrated Master of Arts (MA) programme is through the Humanities and Social Sciences Entrance Examination (HSEE), an IIT Madras specific exam. Admissions to the online degree programme for B.Sc. in Programming and Data Science are done through a Qualifier Process which includes four weeks of instruction in Computational Thinking, Mathematics, Statistics and English.For the postgraduate curriculum, admission to the MTech and MS programmes are through the Graduate Aptitude Test in Engineering (GATE). The Joint Admission Test to MSc (JAM) is the entrance exam for the two-year MSc programme, and other post BSc programmes. MBA candidates are accepted through the Common Admission Test (CAT).\n\n\n=== Rankings ===\nInternationally, IIT Madras was ranked 255 in the QS World University Rankings of 2022. The same rankings ranked it 50 in Asia in 2021 and 17 among BRICS nations in 2019. It was ranked 701–800 in the world by the Academic Ranking of World Universities of 2021.IIT Madras also ranked first among engineering colleges by the National Institutional Ranking Framework (NIRF) in 2020 and first overall. It ranked first in Atal Rankings of Institutions on Innovation Achievements (ARIIA) for three consecutive years from 2019 to 2021.\n\n\n=== Grading System and Student Evaluation ===\nThe Indian Institutes of Technology are under control of the Government of India and therefore have strict rules for grade.\nDepending on the course the evaluation is based on participation in class, attendance, quiz, exam and/or paper. Continuous evaluation is done by course instructors.\nThe Evaluation System of IIT Madras which is also used in other IITs is the Cumulative Grade Point Average with a scale from 0 to 10 which is converted to letters:\n\nCGPA then gets calculated as the cumulative credit-weighted average of the grade points:\nCGPA = (Σ Ci • GPi) / (Σ Ci)\nwhere:\nN is the number of courses\nCi is credits for the ith course\nGPi is grade points for the ith course\nCGPA is the cumulative grade point average\nThe CGPA is not the same as the one commonly used in the United States.\nIn India some credits might be awarded during Bachelor studies for Co-curricular and Extra-curricular Activities, while during the Master Programme this is not allowed.\nThrough agreements with numerous international organisations, IIT grades are accepted from many international organisations like NTU, NUS and DAAD.\nAdditionally, the attendance of the students is evaluated with VG for very good (always present), G for good (not present every lecture) and P for poor (student was present less than 85% of lectures).\n\n\n=== Academic research programmes ===\nThe institute has departments and advanced research centres across the disciplines of engineering and the pure sciences, and nearly 100 laboratories.Research programmes concern work undertaken by faculty members or specific research groups within departments that award an MS or PhD degree. Research is carried out by scholars admitted into these departmental programmes, under the guidance of their faculty.  Each department makes known its areas of interest to the academic community through handbooks, brochures and bulletins. Topics of interest may be theoretical or experimental. IIT Madras has initiated 16 inter-disciplinary research projects against identified focus areas.\n\n\n=== Partnership with other universities ===\nThe institute maintains academic friendship with educational institutes around the world through faculty exchange programmes. The institute has signed Memoranda of Understanding (MOUs) with foreign universities, resulting in cooperative projects and assignments.\n\n\n=== Industrial Consultancy and Sponsored Research ===\nThrough industrial consultancy, faculty and staff undertake assignments for industry that may include project design, testing and evaluation, or training in new areas of industrial development. Industries and organisations like the Indian Ordnance Factories, reach out to the IIT faculty to undertake assignments channeled through the Centre For Industrial Consultancy and Sponsored Research (ICSR).\nNational organisations sponsor programmes of research by funding projects undertaken by the faculty. Such research is time bound and allows project participants to register for a degree.  Project proposals are usually prepared by the IIT faculty and forwarded to interested organisations, based on the nature of their research and their interest to fund such projects.\nSponsored projects are often vehicles for new resources within departments, and often permit their project staff to register for academic degrees in the institute. All sponsored research activities at the institute are coordinated by ICSR.\nPark\nThe IIT Madras Research Park, the first of its kind to be established in India, functions to propel successful innovation in established companies and provide a nurturing ecosystem to startups through incubation efforts and technical infrastructure. Following its success, 50 research parks were planned as part of Start Up India initiative of the Central Government of India. Corporate clients of IIT Madras Research park include Bharat Heavy Electricals Limited, Saint-Gobain and Forbes Marshall. Ather Energy, Hyperverge and Gyandata are some of the startups incubated at the Research Park. The Research Park is primarily reason why a very large number of startups are incubated at IIT Madras.\n\n\n=== National Programme on Technology Enhanced Learning (NPTEL) ===\nTo improve the quality of higher education in India, IIT Madras came up with an initiative called NPTEL (National Programme on Technology Enhanced Learning) in the year 2003. As per this initiative, all the IITs, along with the IISc Bangalore would come up with a series of video lecture based courses across all the streams of engineering. This initiative has gained wide popularity in India and the lectures are being used by several engineering students from across India. It is the Largest online repository in the world of courses in engineering, basic sciences and selected humanities and social sciences subjects.\n\n\n=== BSc Degree Programme in Programming and Data Science. ===\nThe institute launched the country\'s first online BSc program in Programming and Data Science. The 116 credit program consists of three levels—Foundation (32 credits), Diploma (48 credits), and Degree (36 credits). The faculty of the program include Madhavan Mukund (Department of Computer Science & Engineering, Chennai Mathematical Institute), Rajesh Kumar (Professor, Department of Humanities and Social Sciences, IIT Madras), Andrew Thangaraj (Professor, Electrical Engineering Department, IIT Madras), Sudarshan Iyengar (Associate Professor, Department of Computer Science and Engineering, IIT Ropar), and several more faculty, instructors and mentors.\n\nThe first batch of 8,154 students who joined the program in 2020 have brought unprecedented diversity: Prathap Haridoss, professor in charge of the online degree programme, said nearly 30% of the learners are working professionals from IT, banking, manufacturing, finance, law, healthcare, marketing and other sectors.The institute has been working with experts from NPTEL to manage the program. Instruction is via recorded videos followed by activity questions. There are at least three sessions per week for each course subject that allow students to interact, discuss and study. Weekly graded assignments, monthly quizzes and an end term final exam are used to award grades as per the IIT Grading System. The in-person quizzes and exams are conducted at the test centres across the country.\nIn additional to a challenging academic curriculum, the students are encouraged to participate in various professional development, skill development and social activities organized by the institute, students and their clubs. In April 2021, the BSc program department organized the  \'Cricket Hackathon 2021\' for students, professionals, and data science enthusiasts. The academic competition was designed for beginners to learn and compete, as well as for professionals to showcase their capabilities in programming, data science, and analytics.\n\n\n== Student activities ==\n\n\n=== Festivals ===\n\n\n==== Shaastra ====\n\nShaastra is the annual technical festival of IIT Madras. It is typically held in the second week of January and is the first ISO 9001:2015 certified student organised festival in the world. It is known for its organisation and activities. Forums include the symposia, workshops, video conferences, lectures, demonstrations, and technical exhibitions. Competitive activities cover design events, programming, simulations, quizzes, applied engineering, speedcubing, robotics, and junk-yard wars.\n\n\n==== Saarang ====\n\nSaarang is the annual social and cultural festival of IIT Madras. It is a five-day-long event held in early January every year and attracts a crowd of 70,000 students and young people from across the country, making it the largest student-run fest in India. Saarang events include speaking, dancing, thespian, quizzing and word games, professional shows (nicknamed proshows) and workshops on music, fashion, art, and dance.\n\n\n==== Department festivals ====\nSeveral departments organise department festivals. Samanvay, Biofest, ExeBit, Wavez, Mechanica, CEA Fest, ChemPlus, Amalgam and Forays are some of the festivals organised by the Department of Management Studies, Computer Science and Engineering, Ocean Engineering, Mechanical Engineering, Civil Engineering, Chemical Engineering, Metallurgical and Materials Engineering and Maths departments respectively. Department of Humanities and Social Sciences hosts Annual Academic Conference.\n\n\n=== The Entrepreneurship Cell ===\nThe Entrepreneurship Cell, IITM, abbreviated as E-Cell IITM, is a student-run body responsible for promoting and inculcating a spirit of entrepreneurial thinking among both the faculty and the student fraternity of IIT Madras. E-Cell was earlier known as "C-TIDES", and was rechristened in 2015 along with a series of organizational changes in an effort to promote greater engagement among students.\nE-Summit is the flagship event of E-Cell and is a three-day-long event typically held in the first week of April. It includes a myriad of events and competitions, such as the Startup Boot Camp, PitchFest, the Intern Fair, a social campaign and workshops, talks a

In [ ]:
print(full_page.content)

Indian Institute of Technology Madras (IIT Madras) is a public technical university located in Chennai, Tamil Nadu, India. As one of the Indian Institutes of Technology (IITs), it is recognized as an Institute of National Importance and has been consistently rated as one of India's most prestigious universities. Founded in 1959 with technical and financial assistance from the former government of West Germany, it was the third IIT established by the Government of India. IIT Madras is ranked the top engineering institute in India by the Ministry of Education's National Institutional Ranking Framework since its inception in 2016.IIT Madras is a residential institute that occupies a 2.5-square-kilometre (0.97 sq mi) campus that was formerly part of the adjoining Guindy National Park. The institute has nearly 600 faculty, 10,000 students and 1,250 administrative and supporting staff. Growing ever since it obtained its charter from the Indian Parliament in 1961, much of the campus is a protected forest, carved out of the Guindy National Park, home to large numbers of chital (spotted deer), black buck, bonnet macaque, and other rare wildlife. A natural lake, deepened in 1988 and 2003, drains most of its rainwater.


== History ==

In 1956, the West German Government offered technical assistance for establishing an institute of higher education in engineering in India. The first Indo-German agreement was signed in Bonn, West Germany in 1959 for the establishment of the Indian Institute of Technology at Madras. IIT Madras was started with technical, academic and financial assistance from the Government of West Germany and was at the time the largest international educational project sponsored by the West German government. The Government of the Federal Republic of Germany has agreed to provide the following assistance in the establishment of a higher technological institute at Madras:

A workshop, laboratory equipment, and a library whose total value does not exceed ₹1.8 crore (US$240,000).
Twenty German professors to serve at the Institute for a period of four to five years
Four German foremen for the workshops of the Institute for 2 years
Facilities for the training of twenty Indian teachers in German institutionsThis has led to several collaborative research efforts with universities and institutions in Germany over the years. Although official support from the German government has ended, several research efforts involving the DAAD programme and Humboldt Fellowships still exist.
The Higher Technological Institute at Madras known as the Indian Institute of Technology, Madras has started functioning The first batch of 120 students was admitted in July 1959 to the first year of the Engineering Course. The institute was inaugurated in 1959, by the then Union Minister for Scientific Research and Cultural Affairs. The first batch had an overall strength of 120 students from across India. In 1961, the IITs were declared to be Institutes of National Importance. The first convocation ceremony was held on 11 July 1964, with Dr. S. Radhakrishnan, then the President of India, delivering the convocation address and awarding the degrees to the inaugural batch of students. The institute got its first women students in the BTech batch of 1966. IIT Madras celebrated its Golden Jubilee in 2009, and its Diamond Jubilee in 2019.


== Campus ==
The main entrance of IIT Madras is on Sardar Patel Road, flanked by the residential districts of Adyar and Velachery. The campus is close to the Raj Bhavan, the official seat of the Governor of Tamil Nadu. Other entrances are located in Velachery (near Anna Garden MTC bus stop, Velachery Main Road), Gandhi Road and Taramani gate (close to Ascendas Tech Park).
The campus is located 10 km (6.2 mi) from the Chennai Airport, 12 km (7.5 mi) from the Chennai Central Railway station, and is connected by city buses. Kasturba Nagar is the nearest station on the Chennai MRTS line.
Two parallel roads, Bonn Avenue and Delhi Avenue, cut through the faculty residential area before they meet at the Gajendra Circle, near the Administrative Block. Buses regularly ply between the Main Gate, Gajendra Circle, the Academic Zone, and the Hostel Zone.


=== Student Hostels ===
Most students at IIT Madras reside in hostels, where extracurricular activities complement the academic routine. The campus has 20 hostels, of which four, Sharavati, Sarayu, Sabarmati and the recently constructed Tunga are exclusively for women. In earlier times, each hostel had attached dining facilities but all of them have since been closed down. Dining facilities are provided in three centralised halls: Nilgiri, Vindhya and Himalaya. Students are assigned to hostels upon matriculation, where they usually reside for the entire duration of their course of study.

The halls of IITM are:

Sindhu, Pampa, Mahanadhi and Tamiraparani are seven-storeyed whereas all the other hostels are three or four storeyed. These four hostels can accommodate more than 1,200 students. The older hostels were all three-storeyed till the early 2000s when extra rooms were added. An additional new floor in the three-storeyed hostels which generally house the undergraduate students and a new block in place of the mess halls of these hostels have been constructed to accommodate for the increased intake of the students. These new blocks could be used as entrances for these hostels. As of 2020, Mandakini has been demolished and a multi-storey block is under construction, with provision to accommodate approximately 1000 students.


=== Facilities ===
IIT Madras provides residential accommodation for its students, faculty, administrative and supporting staff, and their families. The residential houses employ private caterers. The self-contained campus includes two schools               (Vanavani and Kendriya Vidyalaya), three temples (Jalakanteshwara, Durga Peliamman and Ganapathi), three bank branches (SBI, ICICI, Canara Bank), a hospital, shopping centres, food shops, a gym, sleeping room and cricket, football, hockey and badminton stadiums. Internet is available in the academic zone and the faculty and staff residential zone. Earlier Internet was limited in hostel-zone from 2:00 pm till midnight and from 5:00 am to 8:00 am, but increasing demand during academic semester led to round-the-clock Internet service.IIT Madras also has supercomputing capability, with the IBM Virgo Super Cluster with 97 teraflops worth of computational power.


== Organisation and administration ==


=== Governance ===
IIT Madras is an autonomous statutory organisation functioning within the Institutes of Technology Act. The sixteen IITs are administered centrally by the IIT Council, an apex body established by the Government of India. The Minister of Human Resources and Development is the chairman of the council. Each institute has a Board of Governors responsible for its administration and control.
The Senate comprises all professors of the Institute and decides its academic policy. It controls and approves the curriculum, courses, examinations, and results. It appoints committees to examine specific academic matters. The Director of the institute serves as the Chairman of the Senate. The current director is Kamakoti Veezhinathan.Three Senate Sub-Committees – The Board of Academic Research, The Board of Academic Courses and The Board of Students – help in academic administration and in the operations of the institute. The Finance Committee advises on matters of financial policy, while the Building and Works Committee advises on buildings and infrastructure. The Board of Industrial Consultancy and Sponsored Research addresses industrial consultancy and the Library Advisory Committee oversees library matters.


=== Departments ===
Aerospace Engineering
Applied Mechanics
Biotechnology (Bhupat and Jyoti Mehta School of Biosciences)
Chemical Engineering
Chemistry
Civil Engineering
Computer Science and Engineering
Electrical Engineering
Engineering Design
Humanities and Social Sciences
Mechanical Engineering
Management Studies
Metallurgical and Materials Engineering
Mathematics
Ocean Engineering
Physics


== Academics ==
IIT Madras offers undergraduate, postgraduate and research degrees across 16 disciplines in Engineering, Sciences, Humanities and Management. About 360 faculty belonging to science and engineering departments and centres of the Institute are engaged in teaching, research and industrial consultancy.
The institute has 16 academic departments and advanced research centres across disciplines of engineering and pure sciences, with nearly 100 laboratories. The academic calendar is organised around the semester. Each semester provides a minimum of seventy days of instruction in English. Students are evaluated on a continuous basis throughout the semester. Evaluation is done by the faculty, a consequence of the autonomous status granted to the institute. Research work is evaluated on the basis of the review thesis by peer examiners both from within the country and abroad. Ordinances that govern the academic programme of study are prepared by the Senate, the highest academic body within the institute.


=== Admission tests ===
For the undergraduate curriculum, admission to the BTech and Dual Degree (BSc + MSc or BTech + MTech) programme is done through the Joint Entrance Examination – Advanced (JEE-Advanced). IIT Madras conducted JEE Advanced in 2017. Admission to the five-year integrated Master of Arts (MA) programme is through the Humanities and Social Sciences Entrance Examination (HSEE), an IIT Madras specific exam. Admissions to the online degree programme for B.Sc. in Programming and Data Science are done through a Qualifier Process which includes four weeks of instruction in Computational Thinking, Mathematics, Statistics and English.For the postgraduate curriculum, admission to the MTech and MS programmes are through the Graduate Aptitude Test in Engineering (GATE). The Joint Admission Test to MSc (JAM) is the entrance exam for the two-year MSc programme, and other post BSc programmes. MBA candidates are accepted through the Common Admission Test (CAT).


=== Rankings ===
Internationally, IIT Madras was ranked 255 in the QS World University Rankings of 2022. The same rankings ranked it 50 in Asia in 2021 and 17 among BRICS nations in 2019. It was ranked 701–800 in the world by the Academic Ranking of World Universities of 2021.IIT Madras also ranked first among engineering colleges by the National Institutional Ranking Framework (NIRF) in 2020 and first overall. It ranked first in Atal Rankings of Institutions on Innovation Achievements (ARIIA) for three consecutive years from 2019 to 2021.


=== Grading System and Student Evaluation ===
The Indian Institutes of Technology are under control of the Government of India and therefore have strict rules for grade.
Depending on the course the evaluation is based on participation in class, attendance, quiz, exam and/or paper. Continuous evaluation is done by course instructors.
The Evaluation System of IIT Madras which is also used in other IITs is the Cumulative Grade Point Average with a scale from 0 to 10 which is converted to letters:

CGPA then gets calculated as the cumulative credit-weighted average of the grade points:
CGPA = (Σ Ci • GPi) / (Σ Ci)
where:
N is the number of courses
Ci is credits for the ith course
GPi is grade points for the ith course
CGPA is the cumulative grade point average
The CGPA is not the same as the one commonly used in the United States.
In India some credits might be awarded during Bachelor studies for Co-curricular and Extra-curricular Activities, while during the Master Programme this is not allowed.
Through agreements with numerous international organisations, IIT grades are accepted from many international organisations like NTU, NUS and DAAD.
Additionally, the attendance of the students is evaluated with VG for very good (always present), G for good (not present every lecture) and P for poor (student was present less than 85% of lectures).


=== Academic research programmes ===
The institute has departments and advanced research centres across the disciplines of engineering and the pure sciences, and nearly 100 laboratories.Research programmes concern work undertaken by faculty members or specific research groups within departments that award an MS or PhD degree. Research is carried out by scholars admitted into these departmental programmes, under the guidance of their faculty.  Each department makes known its areas of interest to the academic community through handbooks, brochures and bulletins. Topics of interest may be theoretical or experimental. IIT Madras has initiated 16 inter-disciplinary research projects against identified focus areas.


=== Partnership with other universities ===
The institute maintains academic friendship with educational institutes around the world through faculty exchange programmes. The institute has signed Memoranda of Understanding (MOUs) with foreign universities, resulting in cooperative projects and assignments.


=== Industrial Consultancy and Sponsored Research ===
Through industrial consultancy, faculty and staff undertake assignments for industry that may include project design, testing and evaluation, or training in new areas of industrial development. Industries and organisations like the Indian Ordnance Factories, reach out to the IIT faculty to undertake assignments channeled through the Centre For Industrial Consultancy and Sponsored Research (ICSR).
National organisations sponsor programmes of research by funding projects undertaken by the faculty. Such research is time bound and allows project participants to register for a degree.  Project proposals are usually prepared by the IIT faculty and forwarded to interested organisations, based on the nature of their research and their interest to fund such projects.
Sponsored projects are often vehicles for new resources within departments, and often permit their project staff to register for academic degrees in the institute. All sponsored research activities at the institute are coordinated by ICSR.
Park
The IIT Madras Research Park, the first of its kind to be established in India, functions to propel successful innovation in established companies and provide a nurturing ecosystem to startups through incubation efforts and technical infrastructure. Following its success, 50 research parks were planned as part of Start Up India initiative of the Central Government of India. Corporate clients of IIT Madras Research park include Bharat Heavy Electricals Limited, Saint-Gobain and Forbes Marshall. Ather Energy, Hyperverge and Gyandata are some of the startups incubated at the Research Park. The Research Park is primarily reason why a very large number of startups are incubated at IIT Madras.


=== National Programme on Technology Enhanced Learning (NPTEL) ===
To improve the quality of higher education in India, IIT Madras came up with an initiative called NPTEL (National Programme on Technology Enhanced Learning) in the year 2003. As per this initiative, all the IITs, along with the IISc Bangalore would come up with a series of video lecture based courses across all the streams of engineering. This initiative has gained wide popularity in India and the lectures are being used by several engineering students from across India. It is the Largest online repository in the world of courses in engineering, basic sciences and selected humanities and social sciences subjects.


=== BSc Degree Programme in Programming and Data Science. ===
The institute launched the country's first online BSc program in Programming and Data Science. The 116 credit program consists of three levels—Foundation (32 credits), Diploma (48 credits), and Degree (36 credits). The faculty of the program include Madhavan Mukund (Department of Computer Science & Engineering, Chennai Mathematical Institute), Rajesh Kumar (Professor, Department of Humanities and Social Sciences, IIT Madras), Andrew Thangaraj (Professor, Electrical Engineering Department, IIT Madras), Sudarshan Iyengar (Associate Professor, Department of Computer Science and Engineering, IIT Ropar), and several more faculty, instructors and mentors.

The first batch of 8,154 students who joined the program in 2020 have brought unprecedented diversity: Prathap Haridoss, professor in charge of the online degree programme, said nearly 30% of the learners are working professionals from IT, banking, manufacturing, finance, law, healthcare, marketing and other sectors.The institute has been working with experts from NPTEL to manage the program. Instruction is via recorded videos followed by activity questions. There are at least three sessions per week for each course subject that allow students to interact, discuss and study. Weekly graded assignments, monthly quizzes and an end term final exam are used to award grades as per the IIT Grading System. The in-person quizzes and exams are conducted at the test centres across the country.
In additional to a challenging academic curriculum, the students are encouraged to participate in various professional development, skill development and social activities organized by the institute, students and their clubs. In April 2021, the BSc program department organized the  'Cricket Hackathon 2021' for students, professionals, and data science enthusiasts. The academic competition was designed for beginners to learn and compete, as well as for professionals to showcase their capabilities in programming, data science, and analytics.


== Student activities ==


=== Festivals ===


==== Shaastra ====

Shaastra is the annual technical festival of IIT Madras. It is typically held in the second week of January and is the first ISO 9001:2015 certified student organised festival in the world. It is known for its organisation and activities. Forums include the symposia, workshops, video conferences, lectures, demonstrations, and technical exhibitions. Competitive activities cover design events, programming, simulations, quizzes, applied engineering, speedcubing, robotics, and junk-yard wars.


==== Saarang ====

Saarang is the annual social and cultural festival of IIT Madras. It is a five-day-long event held in early January every year and attracts a crowd of 70,000 students and young people from across the country, making it the largest student-run fest in India. Saarang events include speaking, dancing, thespian, quizzing and word games, professional shows (nicknamed proshows) and workshops on music, fashion, art, and dance.


==== Department festivals ====
Several departments organise department festivals. Samanvay, Biofest, ExeBit, Wavez, Mechanica, CEA Fest, ChemPlus, Amalgam and Forays are some of the festivals organised by the Department of Management Studies, Computer Science and Engineering, Ocean Engineering, Mechanical Engineering, Civil Engineering, Chemical Engineering, Metallurgical and Materials Engineering and Maths departments respectively. Department of Humanities and Social Sciences hosts Annual Academic Conference.


=== The Entrepreneurship Cell ===
The Entrepreneurship Cell, IITM, abbreviated as E-Cell IITM, is a student-run body responsible for promoting and inculcating a spirit of entrepreneurial thinking among both the faculty and the student fraternity of IIT Madras. E-Cell was earlier known as "C-TIDES", and was rechristened in 2015 along with a series of organizational changes in an effort to promote greater engagement among students.

In [ ]:
print(full_page.url)

https://en.wikipedia.org/wiki/IIT_Madras

In [ ]:
print(full_page.references)

['http://www.businessweek.com/smallbiz/news/date/9811/e981130.htm', 'http://www.hindu.com/2009/02/28/stories/2009022854140500.htm', 'http://timesofindia.indiatimes.com/tech/tech-news/IIT-Madras-is-Indias-Stanford/articleshow/46629160.cms', 'http://www.shanghairanking.com/rankings/arwu/2021', 'http://www.thehindu.com/news/cities/chennai/a-helping-hand-to-entrepreneurship/article17856871.ece', 'http://www.thehindu.com/sci-tech/technology/iitm-computer-system-gets-fastest-tag/article3972727.ece', 'http://www.thehindubusinessline.com/news/education/esummit-at-iit-madras-starts-on-april-7/article9620678.ece', 'http://archiv.tu-chemnitz.de/pub/2006/0020/data/MAthesis_EvelynRichter.pdf', 'http://www.oeb.harvard.edu/faculty/mahadevan/mahadevan-oeb.html', 'http://www.csail.mit.edu/user/723', 'http://nms.lcs.mit.edu/~hari/', 'http://ccw.iitm.ac.in/?q=IITMHostels/hinfo', 'http://www.ecell.iitm.ac.in/e-summit/', 'http://nptel.iitm.ac.in/', 'http://nptel.iitm.ac.in/pdf/NPTEL%20Document.pdf', 'http://www.nss.iitm.ac.in/', 'http://placement.iitm.ac.in/academics.html', 'http://respark.iitm.ac.in/', 'http://t5e.iitm.ac.in/', 'http://t5e.iitm.ac.in/2009/12/the-snet-energy-survey-8th-nov/', 'http://www.iitm.ac.in', 'http://www.iitm.ac.in/The%20Institute/', 'http://www.iitm.ac.in/about', 'http://www.iitm.ac.in/aboutcampus', 'http://www.iitm.ac.in/admissiontests', 'http://www.iitsystem.ac.in/IITcouncil/council.jsp', 'http://nptel.ac.in/course.php', 'http://www.frontline.in/static/html/fl2003/stories/20030214007506500.htm', 'http://ofb.gov.in/download/pr/pr_dgof_interview.pdf', 'http://ssbprize.gov.in/Content/Detail.aspx?AID=531', 'http://www.hri.res.in/~pinaki/', 'http://www.macfound.org/site/c.lkLXJ8MQKrH/b.5458019/k.8448/L_Mahadevan.htm', 'http://www.shaastra.org/2013/main', 'http://geohack.toolforge.org/geohack.php?pagename=IIT_Madras&params=12.99151_N_80.23362_E_', 'http://www.worldcat.org/issn/0971-751X', 'http://www.worldcat.org/issn/0971-8257', 'https://drive.google.com/file/d/0B0cmCKgXUt7ceHZ3SUEwa2s5bTg/view', 'https://timesofindia.indiatimes.com/city/chennai/Its-spit-of-anger-vs-kiss-of-love-at-IIT/articleshow/45183914.cms', 'https://timesofindia.indiatimes.com/city/chennai/iit-madras-diamond-jubilee-celebrations-assume-global-proportions-events-to-be-held-in-83-cities/articleshow/70143608.cms', 'https://timesofindia.indiatimes.com/city/chennai/iit-madras-alumnus-is-now-its-new-director/articleshow/88821542.cms', 'https://www.livemint.com/news/india/iit-madras-raises-700-crore-as-endowment-fund-11616957609084.html', 'https://www.ndtv.com/education/iit-madras-to-hold-open-house-to-showcase-student-innovations-2125282', 'https://www.thehindu.com/education/in-1966-she-was-iit-madras-first-woman-civil-engineering-student/article28759995.ece', 'https://www.thehindu.com/news/cities/chennai/chen-society/golden-jubilee-of-iitms-first-batch-of-graduands/article6218293.ece', 'https://www.thehindu.com/news/cities/chennai/iit-madras-named-most-innovative-institute/article38067215.ece', 'https://www.thehindu.com/news/cities/chennai/iitm-turns-60-a-chat-with-first-batch-students/article28744533.ece', 'https://www.thehindu.com/news/national/tamil-nadu/over-8100-join-iit-madras-online-bsc-degree-course/article33295371.ece', 'https://www.thenewsminute.com/tamils/287?amp', 'https://www.topuniversities.com/university-rankings/asian-university-rankings/2021', 'https://www.topuniversities.com/university-rankings/brics-rankings/2019', 'https://www.topuniversities.com/university-rankings/world-university-rankings/2022', 'https://www.youtube.com/watch?v=5485lx6wsao', 'https://aleph.nkp.cz/F/?func=find-c&local_base=aut&ccl_term=ica=ko2008435605&CON_LNG=ENG', 'https://www.projekt-mida.de/reflexicon/indo-german-entanglements-in-science-and-technology-the-indian-institute-of-technology-madras/', 'https://cms.caltech.edu/people/mani', 'https://catalogue.bnf.fr/ark:/12148/cb12442559g', 'https://data.bnf.fr/ark:/12148/cb12442559g', 'https://www.idref.fr/033570418', 'https://id.loc.gov/authorities/names/n50063099', 'https://oir.iitm.ac.in/mou/', 'https://onlinedegree.iitm.ac.in/', 'https://onlinedegree.iitm.ac.in/admissions.html#AD2', 'https://onlinedegree.iitm.ac.in/course_pages/BSCCS1002.html', 'https://onlinedegree.iitm.ac.in/course_pages/BSCHS1001.html', 'https://onlinedegree.iitm.ac.in/course_pages/BSCMA1001.html#9003', 'https://onlinedegree.iitm.ac.in/course_pages/BSCMA1004.html', 'https://research.iitm.ac.in/department_list#:~:text=RESEARCH%20AREAS,-Cellular,%20Molecular%20and&text=Bioinformatics%20and%20Computational%20Biology;%20Biomedical,Molecular%20Genetics%20of%20Plant%20Development.', 'https://respark.iitm.ac.in/iit-madras-launches-worlds-first-ever-online-b-sc-degree-in-programming-and-data-science/', 'https://www.iitm.ac.in/', 'https://www.iitm.ac.in/happenings/press-releases-and-coverages/iit-madras-launches-cricket-hackathon-2021', 'https://www.iitm.ac.in/nirfreports/nirf2016/NIRF-Overall-FullReport.pdf', 'https://www.iitm.ac.in/sites/default/files/Others/annual-budget-2021-22.pdf', 'https://www.iitm.ac.in/the-institute/administration/academic-administration', 'https://nptel.ac.in/', 'https://www.collegesearch.in/exam/jee-advanced/article/top-10-iits-in-india-2018-29-174', 'https://www.ariia.gov.in/Ranking2019.html', 'https://eparlib.nic.in/bitstream/123456789/1530/1/lsd_02_06_02-12-1958.pdf', 'https://eparlib.nic.in/bitstream/123456789/1769/1/lsd_02_08_10-08-1959.pdf', 'https://web.archive.org/web/20060427232338/http://www.iitm.ac.in/The%20Institute/', 'https://web.archive.org/web/20090303061238/http://www.hindu.com/2009/02/28/stories/2009022854140500.htm', 'https://web.archive.org/web/20091115092457/http://www.businessweek.com/smallbiz/news/date/9811/e981130.htm', 'https://web.archive.org/web/20100215010549/http://archiv.tu-chemnitz.de/pub/2006/0020/data/MAthesis_EvelynRichter.pdf', 'https://web.archive.org/web/20120113170811/http://www.nptel.iitm.ac.in/', 'https://web.archive.org/web/20120227163617/http://www.oeb.harvard.edu/faculty/mahadevan/mahadevan-oeb.html', 'https://web.archive.org/web/20120623211803/http://www.nss.iitm.ac.in/', 'https://web.archive.org/web/20120904044551/http://nptel.iitm.ac.in/pdf/NPTEL%20Document.pdf', 'https://web.archive.org/web/20130409125154/http://placement.iitm.ac.in/academics.html', 'https://web.archive.org/web/20130707013747/http://t5e.iitm.ac.in/', 'https://web.archive.org/web/20130907050154/http://www.shaastra.org/2013/main', 'https://web.archive.org/web/20140810091111/http://www.iitsystem.ac.in/IITcouncil/council.jsp', 'https://web.archive.org/web/20141103172852/http://t5e.iitm.ac.in/2009/12/the-snet-energy-survey-8th-nov/', 'https://web.archive.org/web/20161128191932/http://nptel.ac.in/course.php', 'https://web.archive.org/web/20170704084948/http://www.ecell.iitm.ac.in/e-summit/', 'https://ghostarchive.org/varchive/youtube/20211107/5485lx6wsao', 'https://isni.org/isni/000000012314788X', 'https://isni.org/isni/0000000123151926', 'https://www.nirfindia.org/2018/EngineeringRanking.html', 'https://www.nirfindia.org/2019/EngineeringRanking.html', 'https://www.nirfindia.org/2021/EngineeringRanking.html', 'https://www.nirfindia.org/2021/OverallRanking.html', 'https://www.nobelprize.org/prizes/chemistry/2019/goodenough/lecture/', 'https://viaf.org/viaf/168123199', 'https://www.wikidata.org/wiki/Q858662#identifiers', 'https://www.worldcat.org/identities/lccn-n50063099/']

In [ ]:
print(full_page.title)

IIT Madras

In [ ]:
print(full_page.images)

['https://upload.wikimedia.org/wikipedia/commons/f/f2/Blackbuck_white.jpg', 'https://upload.wikimedia.org/wikipedia/commons/1/1b/Brahmaputra_Hostel.jpg', 'https://upload.wikimedia.org/wikipedia/commons/c/c4/Deer_of_IIT_Madras_masatran_0058_0010.jpeg', 'https://upload.wikimedia.org/wikipedia/commons/e/e4/Godavari_Hostel_Entrance.jpg', 'https://upload.wikimedia.org/wikipedia/commons/0/08/Heritage_Center1.jpg', 'https://upload.wikimedia.org/wikipedia/commons/8/85/Pfeil_links.svg', 'https://upload.wikimedia.org/wikipedia/commons/7/76/Pfeil_oben.svg', 'https://upload.wikimedia.org/wikipedia/commons/c/c5/Pfeil_rechts.svg', 'https://upload.wikimedia.org/wikipedia/commons/c/c3/Pfeil_unten.svg', 'https://upload.wikimedia.org/wikipedia/commons/7/71/Sabarmathi_hostel2.jpg', 'https://upload.wikimedia.org/wikipedia/en/4/4a/Commons-logo.svg', 'https://upload.wikimedia.org/wikipedia/en/f/f2/Edit-clear.svg', 'https://upload.wikimedia.org/wikipedia/en/4/41/Flag_of_India.svg', 'https://upload.wikimedia.org/wikipedia/en/6/69/IIT_Madras_Logo.svg', 'https://upload.wikimedia.org/wikipedia/en/8/8a/OOjs_UI_icon_edit-ltr-progressive.svg', 'https://upload.wikimedia.org/wikipedia/en/9/99/Question_book-new.svg', 'https://upload.wikimedia.org/wikipedia/en/9/96/Symbol_category_class.svg']

In [ ]:
#extracting html code of wikipedia page base on any search text
html = wk.page("IIT Madras").html().encode("UTF-8")

In [ ]:
import pandas as pd
df = pd.read_html(html)[4]
print(df)

  Letter Grade  Grade Points                                    in Words
0            S            10     Excellent (top students/high performer)
1            A             9                                   Very Good
2            B             8                                        Good
3            C             7                           Satisfactory Work
4            D             6                               Below Average
5            E             4                           Poor (but passed)
6            U             0                                      Failed
7            W             0  Shortage of attendance (usually below 85%)

# **PDF Scraping**

In [ ]:
import os
import requests
import urllib.request
from urllib.parse import urljoin
from bs4 import BeautifulSoup

!pip install tabula-py
import tabula

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Requirement already satisfied: tabula-py in /usr/local/lib/python3.7/dist-packages (2.4.0)
Requirement already satisfied: distro in /usr/local/lib/python3.7/dist-packages (from tabula-py) (1.7.0)
Requirement already satisfied: numpy in /usr/local/lib/python3.7/dist-packages (from tabula-py) (1.21.6)
Requirement already satisfied: pandas>=0.25.3 in /usr/local/lib/python3.7/dist-packages (from tabula-py) (1.3.5)
Requirement already satisfied: pytz>=2017.3 in /usr/local/lib/python3.7/dist-packages (from pandas>=0.25.3->tabula-py) (2022.1)
Requirement already satisfied: python-dateutil>=2.7.3 in /usr/local/lib/python3.7/dist-packages (from pandas>=0.25.3->tabula-py) (2.8.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.7/dist-packages (from python-dateutil>=2.7.3->pandas>=0.25.3->tabula-py) (1.15.0)
Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
url = "https://www.premierleague.com/publications"

folder_location = r'/content/drive/MyDrive/TDS/premier_league1'
if not os.path.exists(folder_location):
  os.mkdir(folder_location)

In [ ]:
response = requests.get(url)
soup = BeautifulSoup(response.text, "html.parser")

In [ ]:
for link in soup.select("a[href$='.pdf']"):#picking out pdf links from url
  filename = os.path.join(folder_location, link['href'].split('/')[-1])
  with open(filename, 'wb') as f:
    f.write(requests.get(urljoin(url, link['href'])).content)

In [ ]:
df = tabula.read_pdf(folder_location + "/This-is-PL-Interactive-Combined.pdf", pages='18')
df

[                                           Unnamed: 0  \
 0                                                 NaN
 1                                                 NaN
 2                                                 NaN
 3                                                 NaN
 4                                                 NaN
 5                                                 NaN
 6                                                 NaN
 7                                                 NaN
 8                                                 NaN
 9                                               £100m
 10                                                NaN
 11                                                NaN
 12                                     The amount the
 13                                     Premier League
 14                              invests per season in
 15                                 the development of
 16                              community facilities,
 17          sports participation, Central payments to
 18                community and schools clubs 2017/18
 19  programmes, and to The collective and central ...
 20  support the well-being Premier League markets ...
 21                                of players in lower
 22  make using these central payments, leagues. Th...
 23  League also supports all of them to not only i...
 24  the English Football talented players and faci...
 25  League with a further also their local communi...
 26        £100m per season of wider football pyramid.
 27   Solidarity payments The income generated by fans
 28                              and ring-fenced Youth
 29  Development grants. watching compelling matche...
 30                  the Premier League is what allows

                                 Unnamed: 1  Unnamed: 2   Pos Unnamed: 3  \
 0                                      NaN         NaN   1.0        NaN
 1                                      NaN         NaN   2.0        NaN
 2                                      NaN         NaN   3.0        NaN
 3                                      NaN         NaN   4.0        NaN
 4                                      NaN         NaN   5.0        NaN
 5                                      NaN         NaN   6.0        NaN
 6                                      NaN         NaN   7.0        NaN
 7                                      NaN         NaN   8.0        NaN
 8                                      NaN         NaN   9.0        NaN
 9                                      NaN         NaN  10.0        NaN
 10                                     NaN         NaN   NaN        125
 11                                     NaN         NaN   NaN     RAEY S
 12                                     NaN         NaN  11.0        NaN
 13                                     NaN         NaN   NaN        NaN
 14                                     NaN         NaN  12.0        NaN
 15                                     NaN         NaN   NaN        NaN
 16                                     NaN         NaN  13.0        NaN
 17                                     NaN         NaN   NaN        NaN
 18                                     NaN         NaN  14.0        NaN
 19      our clubs to remain as competitive         NaN   NaN        NaN
 20        as possible. The investment they         NaN  15.0        NaN
 21                                     NaN         NaN   NaN        NaN
 22                                     NaN         NaN  16.0        NaN
 23       creates safer and more accessible         NaN   NaN        NaN
 24  stadia for fans. This on-pitch success         NaN  17.0        NaN
 25    enables the responsible distribution         NaN   NaN        NaN
 26       of investment through the rest of         NaN  18.0        NaN
 27          the football pyramid to ensure         NaN   NaN        NaN
 28                                     NaN         NaN  19.0        NaN
 29    participation in the game can thrive         NaN   NaN        NaN
 30                         at every level.         NaN  20.0        NaN

                       Club     W     D     L    GD    Pts Total payment
 0          Manchester City  32.0   4.0   2.0  79.0  100.0       £149.4m
 1        Manchester United  25.0   6.0   7.0  40.0   81.0       £149.8m
 2        Tottenham Hotspur  23.0   8.0   7.0  38.0   77.0       £144.4m
 3                Liverpool  21.0  12.0   5.0  46.0   75.0       £145.9m
 4                  Chelsea  21.0   7.0  10.0  24.0   70.0       £141.7m
 5                  Arsenal  19.0   6.0  13.0  23.0   63.0       £142.0m
 6                  Burnley  14.0  12.0  12.0  -3.0   54.0       £119.8m
 7                  Everton  13.0  10.0  15.0 -14.0   49.0       £128.0m
 8           Leicester City  12.0  11.0  15.0  -4.0   47.0       £118.2m
 9         Newcastle United  12.0   8.0  18.0  -8.0   44.0       £123.0m
 10                     NaN   NaN   NaN   NaN   NaN    NaN           NaN
 11                     NaN   NaN   NaN   NaN   NaN    NaN           NaN
 12          Crystal Palace  11.0  11.0  16.0 -10.0   44.0       £114.3m
 13                     NaN   NaN   NaN   NaN   NaN    NaN           NaN
 14         AFC Bournemouth  11.0  11.0  16.0 -16.0   44.0       £111.2m
 15                     NaN   NaN   NaN   NaN   NaN    NaN           NaN
 16         West Ham United  10.0  12.0  16.0 -20.0   42.0       £116.1m
 17                     NaN   NaN   NaN   NaN   NaN    NaN           NaN
 18                 Watford  11.0   8.0  19.0 -20.0   41.0       £106.3m
 19                     NaN   NaN   NaN   NaN   NaN    NaN           NaN
 20  Brighton & Hove Albion   9.0  13.0  16.0 -20.0   40.0       £107.7m
 21                     NaN   NaN   NaN   NaN   NaN    NaN           NaN
 22       Huddersfield Town   9.0  10.0  19.0 -30.0   37.0       £102.4m
 23                     NaN   NaN   NaN   NaN   NaN    NaN           NaN
 24             Southampton   7.0  15.0  16.0 -19.0   36.0       £107.2m
 25                     NaN   NaN   NaN   NaN   NaN    NaN           NaN
 26            Swansea City   8.0   9.0  21.0 -28.0   33.0        £98.5m
 27                     NaN   NaN   NaN   NaN   NaN    NaN           NaN
 28              Stoke City   7.0  12.0  19.0 -33.0   33.0        £98.9m
 29                     NaN   NaN   NaN   NaN   NaN    NaN           NaN
 30    West Bromwich Albion   6.0  13.0  19.0 -25.0   31.0        £94.7m  ]

In [ ]:
from tabula import convert_into
import pandas as pd

convert_into(folder_location + "/This-is-PL-Interactive-Combined.pdf", folder_location + '/table_output.csv', output_format="csv", pages="18", area=[[275,504,640,900]])
op = pd.read_csv(folder_location+'/table_output.csv')
op

,Pos,Unnamed: 1,Club,W,D,L,GD,Pts,Total payment
0,1.0,NaN,Manchester City,32.0,4.0,2.0,79.0,100.0,£149.4m
1,2.0,NaN,Manchester United,25.0,6.0,7.0,40.0,81.0,£149.8m
2,3.0,NaN,Tottenham Hotspur,23.0,8.0,7.0,38.0,77.0,£144.4m
3,4.0,NaN,Liverpool,21.0,12.0,5.0,46.0,75.0,£145.9m
4,5.0,NaN,Chelsea,21.0,7.0,10.0,24.0,70.0,£141.7m
5,6.0,NaN,Arsenal,19.0,6.0,13.0,23.0,63.0,£142.0m
6,7.0,NaN,Burnley,14.0,12.0,12.0,-3.0,54.0,£119.8m
7,8.0,NaN,Everton,13.0,10.0,15.0,-14.0,49.0,£128.0m
8,9.0,NaN,Leicester City,12.0,11.0,15.0,-4.0,47.0,£118.2m
9,10.0,NaN,Newcastle United,12.0,8.0,18.0,-8.0,44.0,£123.0m
10,NaN,125,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,NaN,E RY SA,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,11.0,NaN,Crystal Palace,11.0,11.0,16.0,-10.0,44.0,£114.3m
13,12.0,NaN,AFC Bournemouth,11.0,11.0,16.0,-16.0,44.0,£111.2m
14,13.0,NaN,West Ham United,10.0,12.0,16.0,-20.0,42.0,£116.1m
15,14.0,NaN,Watford,11.0,8.0,19.0,-20.0,41.0,£106.3m
16,15.0,NaN,Brighton & Hove Albion,9.0,13.0,16.0,-20.0,40.0,£107.7m
17,16.0,NaN,Huddersfield Town,9.0,10.0,19.0,-30.0,37.0,£102.4m
18,17.0,NaN,Southampton,7.0,15.0,16.0,-19.0,36.0,£107.2m
19,18.0,NaN,Swansea City,8.0,9.0,21.0,-28.0,33.0,£98.5m
20,19.0,NaN,Stoke City,7.0,12.0,19.0,-33.0,33.0,£98.9m
21,20.0,NaN,West Bromwich Albion,6.0,13.0,19.0,-25.0,31.0,£94.7m

In [ ]:
import pandas as pd

table = pd.read_excel("/content/drive/MyDrive/TDS/data/IFCB2009_85.xlsx")
table

,BANK,IFSC,BRANCH,ADDRESS,CITY 1,CITY2,STATE,PHONE
0,LAXMI VILAS BANK,LAVB0000101,CHENNAI ZO,"189,IST FLOOR,AARTHI CHAMBERS, ANNASALAI,CHENN...",CHENNAI,CHENNAI,TAMIL NADU,0
1,LAXMI VILAS BANK,LAVB0000102,ACCOUNTS DEPT,"ADMINISTRATIVE OFFICE,NO2,SALEM MAIN ROAD,KATH...",KARUR,KARUR,TAMIL NADU,0
2,LAXMI VILAS BANK,LAVB0000103,ADONI,12 BY 510 MUNICIPAL MAIN ROAD P B NO 17ADONI 5...,KURNOOL,ADONI,ANDHRA PRADESH,252427
3,LAXMI VILAS BANK,LAVB0000104,AMBUR,"NO 87, BROAD BAZAARP B NO 35 AMBUR635802 VELLORE",VELLORE,AMBUR,TAMIL NADU,242126
4,LAXMI VILAS BANK,LAVB0000105,ANBIL,"2 BY 237,MAIN ROAD MANGAMMALPURAM,ANBIL 621 70...",TIRUCHIRAPALLI,LALGUDI,TAMIL NADU,2541287
...,...,...,...,...,...,...,...,...
596,LAXMI VILAS BANK,LAVB0000995,PERSONAL BANKING BRANCH ABHIRAMAPURAM,NO 4 ABHIRAMAPURAM FOURTH STREET ALWARPET CHEN...,CHENNAI,CHENNAI,TAMIL NADU,0
597,LAXMI VILAS BANK,LAVB0000996,"COMMERCIAL BANKING BRANCH,CHENNAI",SRINIVAS TOWERS NO.5 CENOTAPH ROAD TEYNAMPET C...,CHENNAI,CHENNAI,TAMIL NADU,0
598,LAXMI VILAS BANK,LAVB0000997,PERSONAL BANKING BRANCH LANGFORD,GROUND FLOOR GLOBAL TECH PARK NO 11 O SHAUGHNE...,BENGALURU,BENGALURU,KARNATAKA,0
599,LAXMI VILAS BANK,LAVB0000998,DPCELL,NO 776 SAKTHI TOWERS 4TH FLOORANNASALAI CHENNA...,CHENNAI,CHENNAI,TAMIL NADU,0
600,LAXMI VILAS BANK,LAVB0000999,ATM CELL CHENNAI,189 IST FLOOR AARTHI CHAMBERS ANNASALAI CHENNA...,CHENNAI,CHENNAI,TAMIL NADU,0

In [ ]:
table['CITY 1'].value_counts()

CHENNAI          41
COIMBATORE       29
SALEM            22
KARUR            21
ERODE            21
                 ..
BELGAUM           1
KOLAR             1
BHILWARA          1
BAGALKOT          1
VISAKHAPATNAM     1
Name: CITY 1, Length: 173, dtype: int64

In [ ]:
import numpy as np
import pandas as pd
import statsmodels.api as sm
import matplotlib.pyplot as plt
import seaborn as sns
sns.set()
from sklearn.cluster import KMeans

data = pd.read_excel("/content/drive/MyDrive/TDS/data/TDS_Week_5_Dataset_2.xlsx")
data

x=data.iloc[:,1:]

kmeans = KMeans(n_clusters = 7, random_state=1729)
kmeans.fit(x)

# identified_clusters = kmeans.fit_predict(x)
# identified_clusters
# print(identified_clusters)


merged = x.merge(data['record number'],left_index = True, right_index = True)
details = [(name,cluster) for name, cluster in zip(merged['record number'],kmeans.labels_)]
for detail in details:
    print(detail)

(0.0, 6)
(1.0, 6)
(2.0, 6)
(3.0, 6)
(4.0, 6)
(5.0, 5)
(6.0, 6)
(7.0, 6)
(8.0, 6)
(9.0, 6)
(10.0, 6)
(11.0, 6)
(12.0, 6)
(13.0, 6)
(14.0, 6)
(15.0, 6)
(16.0, 6)
(17.0, 6)
(18.0, 5)
(19.0, 5)
(20.0, 5)
(21.0, 5)
(22.0, 0)
(23.0, 6)
(24.0, 5)
(25.0, 0)
(26.0, 1)
(27.0, 6)
(28.0, 3)
(29.0, 5)
(30.0, 5)
(31.0, 1)
(32.0, 0)
(33.0, 5)
(34.0, 3)
(35.0, 5)
(36.0, 5)
(37.0, 5)
(38.0, 5)
(39.0, 5)
(40.0, 0)
(41.0, 5)
(42.0, 5)
(43.0, 5)
(44.0, 3)
(45.0, 5)
(46.0, 1)
(47.0, 5)
(48.0, 5)
(49.0, 5)
(50.0, 5)
(51.0, 5)
(52.0, 5)
(53.0, 3)
(54.0, 5)
(55.0, 5)
(56.0, 3)
(57.0, 5)
(58.0, 5)
(59.0, 5)
(60.0, 3)
(61.0, 5)
(62.0, 0)
(63.0, 5)
(64.0, 5)
(65.0, 1)
(66.0, 5)
(67.0, 1)
(68.0, 1)
(69.0, 3)
(70.0, 5)
(71.0, 5)
(72.0, 1)
(73.0, 5)
(74.0, 3)
(75.0, 5)
(76.0, 0)
(77.0, 5)
(78.0, 0)
(79.0, 0)
(80.0, 3)
(81.0, 1)
(82.0, 5)
(83.0, 5)
(84.0, 3)
(85.0, 5)
(86.0, 5)
(87.0, 0)
(88.0, 3)
(89.0, 5)
(90.0, 5)
(91.0, 5)
(92.0, 5)
(93.0, 0)
(94.0, 3)
(95.0, 0)
(96.0, 5)
(97.0, 5)
(98.0, 1)
(99.0, 5)
(100.0, 1)
(101.0, 3)
(102.0, 5)
(103.0, 5)
(104.0, 3)
(105.0, 0)
(106.0, 5)
(107.0, 0)
(108.0, 1)
(109.0, 3)
(110.0, 1)
(111.0, 3)
(112.0, 3)
(113.0, 5)
(114.0, 0)
(115.0, 3)
(116.0, 5)
(117.0, 1)
(118.0, 0)
(119.0, 5)
(120.0, 3)
(121.0, 5)
(122.0, 1)
(123.0, 0)
(124.0, 1)
(125.0, 3)
(126.0, 0)
(127.0, 3)
(128.0, 1)
(129.0, 3)
(130.0, 5)
(131.0, 1)
(132.0, 1)
(133.0, 0)
(134.0, 3)
(135.0, 3)
(136.0, 3)
(137.0, 1)
(138.0, 5)
(139.0, 5)
(140.0, 1)
(141.0, 3)
(142.0, 3)
(143.0, 3)
(144.0, 1)
(145.0, 3)
(146.0, 5)
(147.0, 3)
(148.0, 3)
(149.0, 3)
(150.0, 3)
(151.0, 3)
(152.0, 0)
(153.0, 1)
(154.0, 3)
(155.0, 0)
(156.0, 0)
(157.0, 1)
(158.0, 0)
(159.0, 3)
(160.0, 0)
(161.0, 0)
(162.0, 3)
(163.0, 1)
(164.0, 3)
(165.0, 3)
(166.0, 3)
(167.0, 0)
(168.0, 1)
(169.0, 0)
(170.0, 3)
(171.0, 0)
(172.0, 3)
(173.0, 4)
(174.0, 3)
(175.0, 3)
(176.0, 0)
(177.0, 0)
(178.0, 1)
(179.0, 0)
(180.0, 3)
(181.0, 0)
(182.0, 3)
(183.0, 3)
(184.0, 3)
(185.0, 0)
(186.0, 3)
(187.0, 1)
(188.0, 0)
(189.0, 3)
(190.0, 3)
(191.0, 0)
(192.0, 1)
(193.0, 0)
(194.0, 0)
(195.0, 0)
(196.0, 3)
(197.0, 3)
(198.0, 3)
(199.0, 0)
(200.0, 0)
(201.0, 3)
(202.0, 3)
(203.0, 3)
(204.0, 3)
(205.0, 0)
(206.0, 3)
(207.0, 1)
(208.0, 3)
(209.0, 0)
(210.0, 3)
(211.0, 0)
(212.0, 0)
(213.0, 3)
(214.0, 3)
(215.0, 3)
(216.0, 0)
(217.0, 3)
(218.0, 0)
(219.0, 3)
(220.0, 0)
(221.0, 3)
(222.0, 3)
(223.0, 3)
(224.0, 3)
(225.0, 3)
(226.0, 3)
(227.0, 0)
(228.0, 3)
(229.0, 3)
(230.0, 3)
(231.0, 3)
(232.0, 3)
(233.0, 3)
(234.0, 0)
(235.0, 0)
(236.0, 3)
(237.0, 0)
(238.0, 0)
(239.0, 3)
(240.0, 0)
(241.0, 3)
(242.0, 0)
(243.0, 1)
(244.0, 6)
(245.0, 1)
(246.0, 0)
(247.0, 0)
(248.0, 3)
(249.0, 0)
(250.0, 0)
(251.0, 0)
(252.0, 3)
(253.0, 0)
(254.0, 1)
(255.0, 3)
(256.0, 3)
(257.0, 3)
(258.0, 0)
(259.0, 3)
(260.0, 0)
(261.0, 3)
(262.0, 3)
(263.0, 0)
(264.0, 3)
(265.0, 3)
(266.0, 0)
(267.0, 3)
(268.0, 3)
(269.0, 3)
(270.0, 0)
(271.0, 0)
(272.0, 0)
(273.0, 3)
(274.0, 3)
(275.0, 3)
(276.0, 3)
(277.0, 1)
(278.0, 3)
(279.0, 3)
(280.0, 1)
(281.0, 1)
(282.0, 3)
(283.0, 1)
(284.0, 0)
(285.0, 3)
(286.0, 1)
(287.0, 3)
(288.0, 0)
(289.0, 0)
(290.0, 0)
(291.0, 3)
(292.0, 3)
(293.0, 0)
(294.0, 3)
(295.0, 3)
(296.0, 1)
(297.0, 3)
(298.0, 0)
(299.0, 0)
(300.0, 0)
(301.0, 3)
(302.0, 3)
(303.0, 3)
(304.0, 0)
(305.0, 3)
(306.0, 0)
(307.0, 0)
(308.0, 4)
(309.0, 0)
(310.0, 1)
(311.0, 0)
(312.0, 0)
(313.0, 3)
(314.0, 0)
(315.0, 3)
(316.0, 0)
(317.0, 0)
(318.0, 3)
(319.0, 4)
(320.0, 0)
(321.0, 0)
(322.0, 0)
(323.0, 3)
(324.0, 1)
(325.0, 0)
(326.0, 3)
(327.0, 0)
(328.0, 0)
(329.0, 3)
(330.0, 0)
(331.0, 3)
(332.0, 0)
(333.0, 0)
(334.0, 0)
(335.0, 0)
(336.0, 1)
(337.0, 1)
(338.0, 3)
(339.0, 3)
(340.0, 0)
(341.0, 0)
(342.0, 1)
(343.0, 3)
(344.0, 3)
(345.0, 3)
(346.0, 3)
(347.0, 1)
(348.0, 3)
(349.0, 0)
(350.0, 3)
(351.0, 0)
(352.0, 3)
(353.0, 0)
(354.0, 0)
(355.0, 3)
(356.0, 1)
(357.0, 3)
(358.0, 1)
(359.0, 3)
(360.0, 1)
(361.0, 1)
(362.0, 0)
(363.0, 0)
(364.0, 0)
(365.0, 3)
(366.0, 3)
(367.0, 0)
(368.0, 0)
(369.0, 0)
(370.0, 1)
(371.0, 1)
(372.0, 3)
(373.0, 1)
(374.0, 3)
(375.0, 3)
(376.0, 0)
(377.0, 3)
(378.0, 3)
(379.0, 3)
(380.0, 3)
(381.0, 0)
(382.0, 3)
(383.0, 3)
(384.0, 1)
(385.0, 3)
(386.0, 1)
(387.0, 3)
(388.0, 0)
(389.0, 1)
(390.0, 1)
(391.0, 3)
(392.0, 1)
(393.0, 0)
(394.0, 0)
(395.0, 3)
(396.0, 0)
(397.0, 3)
(398.0, 0)
(399.0, 0)
(400.0, 0)
(401.0, 0)
(402.0, 0)
(403.0, 0)
(404.0, 0)
(405.0, 3)
(406.0, 3)
(407.0, 0)
(408.0, 0)
(409.0, 3)
(410.0, 1)
(411.0, 3)
(412.0, 3)
(413.0, 3)
(414.0, 3)
(415.0, 0)
(416.0, 0)
(417.0, 0)
(418.0, 1)
(419.0, 3)
(420.0, 0)
(421.0, 3)
(422.0, 1)
(423.0, 3)
(424.0, 3)
(425.0, 0)
(426.0, 1)
(427.0, 4)
(428.0, 3)
(429.0, 0)
(430.0, 3)
(431.0, 3)
(432.0, 3)
(433.0, 3)
(434.0, 3)
(435.0, 3)
(436.0, 0)
(437.0, 3)
(438.0, 3)
(439.0, 3)
(440.0, 1)
(441.0, 0)
(442.0, 3)
(443.0, 1)
(444.0, 3)
(445.0, 4)
(446.0, 1)
(447.0, 1)
(448.0, 0)
(449.0, 0)
(450.0, 1)
(451.0, 0)
(452.0, 3)
(453.0, 1)
(454.0, 0)
(455.0, 1)
(456.0, 1)
(457.0, 3)
(458.0, 3)
(459.0, 3)
(460.0, 0)
(461.0, 0)
(462.0, 0)
(463.0, 0)
(464.0, 1)
(465.0, 3)
(466.0, 0)
(467.0, 0)
(468.0, 0)
(469.0, 3)
(470.0, 3)
(471.0, 1)
(472.0, 3)
(473.0, 0)
(474.0, 0)
(475.0, 0)
(476.0, 1)
(477.0, 0)
(478.0, 3)
(479.0, 1)
(480.0, 3)
(481.0, 0)
(482.0, 0)
(483.0, 3)
(484.0, 0)
(485.0, 3)
(486.0, 0)
(487.0, 3)
(488.0, 1)
(489.0, 1)
(490.0, 3)
(491.0, 2)
(492.0, 0)
(493.0, 1)
(494.0, 3)
(495.0, 3)
(496.0, 0)
(497.0, 3)
(498.0, 0)
(499.0, 1)
(500.0, 0)
(501.0, 0)
(502.0, 3)
(503.0, 0)
(504.0, 2)
(505.0, 3)
(506.0, 0)
(507.0, 0)
(508.0, 3)
(509.0, 2)
(510.0, 0)
(511.0, 0)
(512.0, 0)
(513.0, 3)
(514.0, 3)
(515.0, 0)
(516.0, 3)
(517.0, 3)
(518.0, 3)
(519.0, 0)
(520.0, 3)
(521.0, 3)
(522.0, 3)
(523.0, 1)
(524.0, 3)
(525.0, 0)
(526.0, 1)
(527.0, 0)
(528.0, 0)
(529.0, 1)
(530.0, 3)
(531.0, 0)
(532.0, 3)
(533.0, 1)
(534.0, 0)
(535.0, 0)
(536.0, 0)
(537.0, 3)
(538.0, 3)
(539.0, 0)
(540.0, 0)
(541.0, 0)
(542.0, 3)
(543.0, 0)
(544.0, 3)
(545.0, 0)
(546.0, 3)
(547.0, 3)
(548.0, 0)
(549.0, 0)
(550.0, 3)
(551.0, 1)
(552.0, 0)
(553.0, 3)
(554.0, 1)
(555.0, 3)
(556.0, 0)
(557.0, 0)
(558.0, 0)
(559.0, 0)
(560.0, 3)
(561.0, 3)
(562.0, 1)
(563.0, 3)
(564.0, 3)
(565.0, 1)
(566.0, 3)
(567.0, 1)
(568.0, 0)
(569.0, 3)
(570.0, 0)
(571.0, 3)
(572.0, 3)
(573.0, 3)
(574.0, 3)
(575.0, 3)
(576.0, 0)
(577.0, 3)
(578.0, 3)
(579.0, 0)
(580.0, 3)
(581.0, 0)
(582.0, 3)
(583.0, 0)
(584.0, 0)
(585.0, 1)
(586.0, 3)
(587.0, 3)
(588.0, 3)
(589.0, 0)
(590.0, 3)
(591.0, 0)
(592.0, 3)
(593.0, 1)
(594.0, 3)
(595.0, 0)
(596.0, 0)
(597.0, 3)
(598.0, 3)
(599.0, 3)
(600.0, 3)
(601.0, 3)
(602.0, 3)
(603.0, 0)
(604.0, 0)
(605.0, 3)
(606.0, 0)
(607.0, 3)
(608.0, 0)
(609.0, 3)
(610.0, 0)
(611.0, 2)
(612.0, 1)
(613.0, 0)
(614.0, 3)
(615.0, 0)
(616.0, 3)
(617.0, 3)
(618.0, 3)
(619.0, 0)
(620.0, 0)
(621.0, 0)
(622.0, 3)
(623.0, 0)
(624.0, 1)
(625.0, 0)
(626.0, 3)
(627.0, 0)
(628.0, 3)
(629.0, 3)
(630.0, 3)
(631.0, 3)
(632.0, 1)
(633.0, 3)
(634.0, 1)
(635.0, 3)
(636.0, 3)
(637.0, 3)
(638.0, 0)
(639.0, 3)
(640.0, 3)
(641.0, 0)
(642.0, 0)
(643.0, 3)
(644.0, 3)
(645.0, 3)
(646.0, 3)
(647.0, 2)
(648.0, 0)
(649.0, 0)
(650.0, 0)
(651.0, 1)
(652.0, 3)
(653.0, 1)
(654.0, 0)
(655.0, 0)
(656.0, 0)
(657.0, 4)
(658.0, 1)
(659.0, 1)
(660.0, 3)
(661.0, 3)
(662.0, 3)
(663.0, 3)
(664.0, 3)
(665.0, 3)
(666.0, 0)
(667.0, 3)
(668.0, 3)
(669.0, 2)
(670.0, 0)
(671.0, 1)
(672.0, 2)
(673.0, 3)
(674.0, 3)
(675.0, 3)
(676.0, 0)
(677.0, 3)
(678.0, 3)
(679.0, 0)
(680.0, 0)
(681.0, 0)
(682.0, 2)
(683.0, 1)
(684.0, 2)
(685.0, 0)
(686.0, 3)
(687.0, 3)
(688.0, 1)
(689.0, 0)
(690.0, 0)
(691.0, 0)
(692.0, 0)
(693.0, 0)
(694.0, 0)
(695.0, 3)
(696.0, 3)
(697.0, 0)
(698.0, 3)
(699.0, 0)
(700.0, 0)
(701.0, 4)
(702.0, 2)
(703.0, 1)
(704.0, 0)
(705.0, 0)
(706.0, 0)
(707.0, 0)
(708.0, 3)
(709.0, 0)
(710.0, 0)
(711.0, 2)
(712.0, 4)
(713.0, 0)
(714.0, 0)
(715.0, 0)
(716.0, 0)
(717.0, 1)
(718.0, 3)
(719.0, 3)
(720.0, 3)
(721.0, 3)
(722.0, 1)
(723.0, 2)
(724.0, 0)
(725.0, 4)
(726.0, 3)
(727.0, 0)
(728.0, 0)
(729.0, 0)
(730.0, 0)
(731.0, 0)
(732.0, 3)
(733.0, 3)
(734.0, 0)
(735.0, 1)
(736.0, 1)
(737.0, 3)
(738.0, 0)
(739.0, 0)
(740.0, 0)
(741.0, 0)
(742.0, 1)
(743.0, 3)
(744.0, 0)
(745.0, 0)
(746.0, 0)
(747.0, 0)
(748.0, 0)
(749.0, 1)
(750.0, 0)
(751.0, 1)
(752.0, 0)
(753.0, 3)
(754.0, 0)
(755.0, 3)
(756.0, 0)
(757.0, 0)
(758.0, 2)
(759.0, 0)
(760.0, 0)
(761.0, 0)
(762.0, 3)
(763.0, 0)
(764.0, 0)
(765.0, 2)
(766.0, 0)
(767.0, 0)
(768.0, 0)
(769.0, 3)
(770.0, 2)
(771.0, 0)
(772.0, 3)
(773.0, 0)
(774.0, 3)
(775.0, 0)
(776.0, 1)
(777.0, 2)
(778.0, 0)
(779.0, 0)
(780.0, 3)
(781.0, 3)
(782.0, 0)
(783.0, 0)
(784.0, 0)
(785.0, 1)
(786.0, 2)
(787.0, 0)
(788.0, 2)
(789.0, 0)
(790.0, 3)
(791.0, 0)
(792.0, 3)
(793.0, 0)
(794.0, 0)
(795.0, 4)
(796.0, 3)
(797.0, 2)
(798.0, 1)
(799.0, 1)
(800.0, 0)
(801.0, 3)
(802.0, 3)
(803.0, 0)
(804.0, 2)
(805.0, 0)
(806.0, 0)
(807.0, 0)
(808.0, 0)
(809.0, 0)
(810.0, 3)
(811.0, 1)
(812.0, 0)
(813.0, 0)
(814.0, 2)
(815.0, 1)
(816.0, 2)
(817.0, 3)
(818.0, 2)
(819.0, 3)
(820.0, 3)
(821.0, 3)
(822.0, 0)
(823.0, 3)
(824.0, 2)
(825.0, 0)
(826.0, 0)
(827.0, 3)
(828.0, 2)
(829.0, 2)
(830.0, 2)
(831.0, 0)
(832.0, 0)
(833.0, 0)
(834.0, 2)
(835.0, 0)
(836.0, 2)
(837.0, 3)
(838.0, 0)
(839.0, 3)
(840.0, 0)
(841.0, 0)
(842.0, 0)
(843.0, 0)
(844.0, 3)
(845.0, 3)
(846.0, 3)
(847.0, 3)
(848.0, 0)
(849.0, 3)
(850.0, 0)
(851.0, 3)
(852.0, 0)
(853.0, 0)
(854.0, 0)
(855.0, 0)
(856.0, 0)
(857.0, 0)
(858.0, 2)
(859.0, 0)
(860.0, 2)
(861.0, 3)
(862.0, 3)
(863.0, 3)
(864.0, 1)
(865.0, 2)
(866.0, 1)
(867.0, 3)
(868.0, 2)
(869.0, 1)
(870.0, 1)
(871.0, 1)
(872.0, 2)
(873.0, 2)
(874.0, 3)
(875.0, 0)
(876.0, 0)
(877.0, 0)
(878.0, 1)
(879.0, 3)
(880.0, 1)
(881.0, 2)
(882.0, 3)
(883.0, 2)
(884.0, 2)
(885.0, 0)
(886.0, 0)
(887.0, 0)
(888.0, 0)
(889.0, 1)
(890.0, 2)
(891.0, 2)
(892.0, 4)
(893.0, 3)
(894.0, 2)
(895.0, 2)
(896.0, 1)
(897.0, 0)
(898.0, 2)
(899.0, 0)
(900.0, 3)
(901.0, 0)
(902.0, 3)
(903.0, 2)
(904.0, 0)
(905.0, 3)
(906.0, 0)
(907.0, 0)
(908.0, 2)
(909.0, 3)
(910.0, 0)
(911.0, 0)
(912.0, 0)
(913.0, 0)
(914.0, 0)
(915.0, 0)
(916.0, 2)
(917.0, 0)
(918.0, 2)
(919.0, 3)
(920.0, 3)
(921.0, 2)
(922.0, 2)
(923.0, 0)
(924.0, 3)
(925.0, 2)
(926.0, 3)
(927.0, 3)
(928.0, 0)
(929.0, 0)
(930.0, 1)
(931.0, 3)
(932.0, 3)
(933.0, 2)
(934.0, 0)
(935.0, 3)
(936.0, 3)
(937.0, 3)
(938.0, 0)
(939.0, 1)
(940.0, 2)
(941.0, 2)
(942.0, 0)
(943.0, 1)
(944.0, 0)
(945.0, 0)
(946.0, 2)
(947.0, 0)
(948.0, 3)
(949.0, 1)
(950.0, 1)
(951.0, 0)
(952.0, 3)
(953.0, 0)
(954.0, 1)
(955.0, 2)
(956.0, 2)
(957.0, 0)
(958.0, 2)
(959.0, 0)
(960.0, 3)
(961.0, 3)
(962.0, 0)
(963.0, 3)
(964.0, 3)
(965.0, 0)
(966.0, 3)
(967.0, 0)
(968.0, 2)
(969.0, 3)
(970.0, 4)
(971.0, 2)
(972.0, 2)
(973.0, 2)
(974.0, 0)
(975.0, 1)
(976.0, 0)
(977.0, 3)
(978.0, 1)
(979.0, 0)
(980.0, 2)
(981.0, 1)
(982.0, 2)
(983.0, 1)
(984.0, 0)
(985.0, 0)
(986.0, 1)
(987.0, 0)
(988.0, 2)
(989.0, 0)
(990.0, 0)
(991.0, 3)
(992.0, 3)
(993.0, 2)
(994.0, 0)
(995.0, 1)
(996.0, 0)
(997.0, 0)
(998.0, 0)
(999.0, 0)
(1000.0, 3)
(1001.0, 3)
(1002.0, 2)
(1003.0, 3)
(1004.0, 2)
(1005.0, 0)
(1006.0, 0)
(1007.0, 0)
(1008.0, 2)
(1009.0, 3)
(1010.0, 0)
(1011.0, 2)
(1012.0, 0)
(1013.0, 2)
(1014.0, 0)
(1015.0, 3)
(1016.0, 2)
(1017.0, 0)
(1018.0, 2)
(1019.0, 2)
(1020.0, 3)
(1021.0, 0)
(1022.0, 0)
(1023.0, 0)
(1024.0, 4)
(1025.0, 4)
(1026.0, 2)
(1027.0, 0)
(1028.0, 1)
(1029.0, 3)
(1030.0, 3)
(1031.0, 0)
(1032.0, 0)
(1033.0, 0)
(1034.0, 2)
(1035.0, 2)
(1036.0, 2)
(1037.0, 3)
(1038.0, 0)
(1039.0, 2)
(1040.0, 2)
(1041.0, 0)
(1042.0, 3)
(1043.0, 0)
(1044.0, 3)
(1045.0, 3)
(1046.0, 2)
(1047.0, 3)
(1048.0, 0)
(1049.0, 2)
(1050.0, 0)
(1051.0, 0)
(1052.0, 2)
(1053.0, 2)
(1054.0, 1)
(1055.0, 0)
(1056.0, 0)
(1057.0, 2)
(1058.0, 2)
(1059.0, 2)
(1060.0, 2)
(1061.0, 3)
(1062.0, 0)
(1063.0, 2)
(1064.0, 2)
(1065.0, 0)
(1066.0, 0)
(1067.0, 2)
(1068.0, 2)
(1069.0, 0)
(1070.0, 3)
(1071.0, 0)
(1072.0, 2)
(1073.0, 2)
(1074.0, 2)
(1075.0, 2)
(1076.0, 0)
(1077.0, 3)
(1078.0, 2)
(1079.0, 2)
(1080.0, 1)
(1081.0, 2)
(1082.0, 0)
(1083.0, 3)
(1084.0, 4)
(1085.0, 1)
(1086.0, 0)
(1087.0, 0)
(1088.0, 0)
(1089.0, 2)
(1090.0, 0)
(1091.0, 0)
(1092.0, 1)
(1093.0, 0)
(1094.0, 2)
(1095.0, 0)
(1096.0, 3)
(1097.0, 0)
(1098.0, 0)
(1099.0, 0)
(1100.0, 3)
(1101.0, 0)
(1102.0, 2)
(1103.0, 0)
(1104.0, 2)
(1105.0, 2)
(1106.0, 2)
(1107.0, 3)
(1108.0, 0)
(1109.0, 1)
(1110.0, 4)
(1111.0, 0)
(1112.0, 0)
(1113.0, 0)
(1114.0, 2)
(1115.0, 3)
(1116.0, 2)
(1117.0, 2)
(1118.0, 0)
(1119.0, 2)
(1120.0, 0)
(1121.0, 2)
(1122.0, 2)
(1123.0, 2)
(1124.0, 0)
(1125.0, 2)
(1126.0, 2)
(1127.0, 0)
(1128.0, 2)
(1129.0, 2)
(1130.0, 2)
(1131.0, 2)
(1132.0, 4)
(1133.0, 1)
(1134.0, 2)
(1135.0, 2)
(1136.0, 1)
(1137.0, 2)
(1138.0, 2)
(1139.0, 4)
(1140.0, 2)
(1141.0, 2)
(1142.0, 1)
(1143.0, 2)
(1144.0, 0)
(1145.0, 0)
(1146.0, 4)
(1147.0, 1)
(1148.0, 3)
(1149.0, 0)
(1150.0, 0)
(1151.0, 2)
(1152.0, 2)
(1153.0, 2)
(1154.0, 2)
(1155.0, 2)
(1156.0, 0)
(1157.0, 2)
(1158.0, 0)
(1159.0, 0)
(1160.0, 0)
(1161.0, 1)
(1162.0, 4)
(1163.0, 4)
(1164.0, 2)
(1165.0, 2)
(1166.0, 2)
(1167.0, 2)
(1168.0, 2)
(1169.0, 0)
(1170.0, 2)
(1171.0, 0)
(1172.0, 3)
(1173.0, 0)
(1174.0, 0)
(1175.0, 2)
(1176.0, 0)
(1177.0, 1)
(1178.0, 2)
(1179.0, 0)
(1180.0, 0)
(1181.0, 0)
(1182.0, 0)
(1183.0, 2)
(1184.0, 1)
(1185.0, 2)
(1186.0, 0)
(1187.0, 0)
(1188.0, 2)
(1189.0, 2)
(1190.0, 1)
(1191.0, 3)
(1192.0, 2)
(1193.0, 2)
(1194.0, 1)
(1195.0, 2)
(1196.0, 0)
(1197.0, 2)
(1198.0, 2)
(1199.0, 2)
(1200.0, 2)
(1201.0, 0)
(1202.0, 2)
(1203.0, 2)
(1204.0, 0)
(1205.0, 0)
(1206.0, 3)
(1207.0, 0)
(1208.0, 1)
(1209.0, 2)
(1210.0, 2)
(1211.0, 0)
(1212.0, 0)
(1213.0, 3)
(1214.0, 5)
(1215.0, 5)
(1216.0, 3)
(1217.0, 3)
(1218.0, 1)
(1219.0, 3)
(1220.0, 3)
(1221.0, 1)
(1222.0, 3)
(1223.0, 3)
(1224.0, 1)

In [ ]:
import numpy as np
import pandas as pd
import statsmodels.api as sm
import matplotlib.pyplot as plt
import seaborn as sns
sns.set()
from sklearn.cluster import KMeans

data = pd.read_excel("/content/drive/MyDrive/TDS/data/TDS_Week_5_Dataset_1.xlsx")
data

data['Failure Type'].replace({'No Failure':0,'Heat Dissipation Failure':0,'Overstrain Failure':0,'Tool Wear Failure':0,'Random Failures': 1, 'Power Failure' : 0}, inplace=True)

data['Failure Type'].value_counts()

0    9982
1      18
Name: Failure Type, dtype: int64

In [ ]:
Q1 = np.percentile(data['Tool wear [min]'], 25,
				interpolation = 'midpoint')

Q3 = np.percentile(data['Tool wear [min]'], 75,
				interpolation = 'midpoint')
IQR = Q3 - Q1

upper = Q3 +1.5*IQR

lower = Q1 - 1.5*IQR

print("Old Shape: ", data.shape)

# Upper bound
upper = np.where(data['Tool wear [min]'] >= (Q3+1.5*IQR))
# Lower bound
lower = np.where(data['Tool wear [min]'] <= (Q1-1.5*IQR))

''' Removing the Outliers '''
data.drop(upper[0], inplace = True)
data.drop(lower[0], inplace = True)

print("New Shape: ", data.shape)

Old Shape:  (10000, 9)
New Shape:  (10000, 9)

# **Pandas Profiling**

In [ ]:
!pip install pandas_profiling==2.9.0
!pip install vision
!pip install pandas==1.2.1
from pandas_profiling import ProfileReport
import pandas as pd
from google.colab import files

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Collecting pandas_profiling==2.9.0
  Downloading pandas_profiling-2.9.0-py2.py3-none-any.whl (258 kB)
     |████████████████████████████████| 258 kB 5.3 MB/s
Requirement already satisfied: numpy>=1.16.0 in /usr/local/lib/python3.7/dist-packages (from pandas_profiling==2.9.0) (1.21.6)
Requirement already satisfied: missingno>=0.4.2 in /usr/local/lib/python3.7/dist-packages (from pandas_profiling==2.9.0) (0.5.1)
Collecting phik>=0.9.10
  Downloading phik-0.12.2-cp37-cp37m-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (690 kB)
     |████████████████████████████████| 690 kB 49.9 MB/s
Requirement already satisfied: matplotlib>=3.2.0 in /usr/local/lib/python3.7/dist-packages (from pandas_profiling==2.9.0) (3.2.2)
Requirement already satisfied: requests>=2.23.0 in /usr/local/lib/python3.7/dist-packages (from pandas_profiling==2.9.0) (2.23.0)
Requirement already satisfied: pandas!=1.0.0,!=1.0.1,!=1.0.2,!=1.1.0,>=0.25.3 in /usr/local/lib/python3.7/dist-packages (from pandas_profiling==2.9.0) (1.3.5)
Requirement already satisfied: scipy>=1.4.1 in /usr/local/lib/python3.7/dist-packages (from pandas_profiling==2.9.0) (1.4.1)
Requirement already satisfied: jinja2>=2.11.1 in /usr/local/lib/python3.7/dist-packages (from pandas_profiling==2.9.0) (2.11.3)
Collecting tangled-up-in-unicode>=0.0.6
  Downloading tangled_up_in_unicode-0.2.0-py3-none-any.whl (4.7 MB)
     |████████████████████████████████| 4.7 MB 46.5 MB/s
Requirement already satisfied: tqdm>=4.43.0 in /usr/local/lib/python3.7/dist-packages (from pandas_profiling==2.9.0) (4.64.0)
Collecting visions[type_image_path]==0.5.0
  Downloading visions-0.5.0-py3-none-any.whl (64 kB)
     |████████████████████████████████| 64 kB 3.5 MB/s
Collecting htmlmin>=0.1.12
  Downloading htmlmin-0.1.12.tar.gz (19 kB)
Requirement already satisfied: ipywidgets>=7.5.1 in /usr/local/lib/python3.7/dist-packages (from pandas_profiling==2.9.0) (7.7.0)
Requirement already satisfied: attrs>=19.3.0 in /usr/local/lib/python3.7/dist-packages (from pandas_profiling==2.9.0) (21.4.0)
Requirement already satisfied: joblib in /usr/local/lib/python3.7/dist-packages (from pandas_profiling==2.9.0) (1.1.0)
Requirement already satisfied: seaborn>=0.10.1 in /usr/local/lib/python3.7/dist-packages (from pandas_profiling==2.9.0) (0.11.2)
Collecting confuse>=1.0.0
  Downloading confuse-1.7.0-py2.py3-none-any.whl (25 kB)
Requirement already satisfied: networkx>=2.4 in /usr/local/lib/python3.7/dist-packages (from visions[type_image_path]==0.5.0->pandas_profiling==2.9.0) (2.6.3)
Requirement already satisfied: Pillow in /usr/local/lib/python3.7/dist-packages (from visions[type_image_path]==0.5.0->pandas_profiling==2.9.0) (7.1.2)
Collecting imagehash
  Downloading ImageHash-4.2.1.tar.gz (812 kB)
     |████████████████████████████████| 812 kB 55.3 MB/s
Requirement already satisfied: pyyaml in /usr/local/lib/python3.7/dist-packages (from confuse>=1.0.0->pandas_profiling==2.9.0) (3.13)
Requirement already satisfied: widgetsnbextension~=3.6.0 in /usr/local/lib/python3.7/dist-packages (from ipywidgets>=7.5.1->pandas_profiling==2.9.0) (3.6.0)
Requirement already satisfied: jupyterlab-widgets>=1.0.0 in /usr/local/lib/python3.7/dist-packages (from ipywidgets>=7.5.1->pandas_profiling==2.9.0) (1.1.0)
Requirement already satisfied: ipykernel>=4.5.1 in /usr/local/lib/python3.7/dist-packages (from ipywidgets>=7.5.1->pandas_profiling==2.9.0) (4.10.1)
Requirement already satisfied: ipython>=4.0.0 in /usr/local/lib/python3.7/dist-packages (from ipywidgets>=7.5.1->pandas_profiling==2.9.0) (5.5.0)
Requirement already satisfied: traitlets>=4.3.1 in /usr/local/lib/python3.7/dist-packages (from ipywidgets>=7.5.1->pandas_profiling==2.9.0) (5.1.1)
Requirement already satisfied: ipython-genutils~=0.2.0 in /usr/local/lib/python3.7/dist-packages (from ipywidgets>=7.5.1->pandas_profiling==2.9.0) (0.2.0)
Requirement already satisfied: nbformat>=4.2.0 in /usr/local/lib/python3.7/dist-packages (from ipywidgets>=7.5.1->pandas_profiling==2.9.0) (5.4.0)
Requirement already satisfied: jupyter-client in /usr/local/lib/python3.7/dist-packages (from ipykernel>=4.5.1->ipywidgets>=7.5.1->pandas_profiling==2.9.0) (5.3.5)
Requirement already satisfied: tornado>=4.0 in /usr/local/lib/python3.7/dist-packages (from ipykernel>=4.5.1->ipywidgets>=7.5.1->pandas_profiling==2.9.0) (5.1.1)
Requirement already satisfied: setuptools>=18.5 in /usr/local/lib/python3.7/dist-packages (from ipython>=4.0.0->ipywidgets>=7.5.1->pandas_profiling==2.9.0) (57.4.0)
Requirement already satisfied: prompt-toolkit<2.0.0,>=1.0.4 in /usr/local/lib/python3.7/dist-packages (from ipython>=4.0.0->ipywidgets>=7.5.1->pandas_profiling==2.9.0) (1.0.18)
Requirement already satisfied: pickleshare in /usr/local/lib/python3.7/dist-packages (from ipython>=4.0.0->ipywidgets>=7.5.1->pandas_profiling==2.9.0) (0.7.5)
Requirement already satisfied: simplegeneric>0.8 in /usr/local/lib/python3.7/dist-packages (from ipython>=4.0.0->ipywidgets>=7.5.1->pandas_profiling==2.9.0) (0.8.1)
Requirement already satisfied: decorator in /usr/local/lib/python3.7/dist-packages (from ipython>=4.0.0->ipywidgets>=7.5.1->pandas_profiling==2.9.0) (4.4.2)
Requirement already satisfied: pexpect in /usr/local/lib/python3.7/dist-packages (from ipython>=4.0.0->ipywidgets>=7.5.1->pandas_profiling==2.9.0) (4.8.0)
Requirement already satisfied: pygments in /usr/local/lib/python3.7/dist-packages (from ipython>=4.0.0->ipywidgets>=7.5.1->pandas_profiling==2.9.0) (2.6.1)
Requirement already satisfied: MarkupSafe>=0.23 in /usr/local/lib/python3.7/dist-packages (from jinja2>=2.11.1->pandas_profiling==2.9.0) (2.0.1)
Requirement already satisfied: python-dateutil>=2.1 in /usr/local/lib/python3.7/dist-packages (from matplotlib>=3.2.0->pandas_profiling==2.9.0) (2.8.2)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.7/dist-packages (from matplotlib>=3.2.0->pandas_profiling==2.9.0) (0.11.0)
Requirement already satisfied: pyparsing!=2.0.4,!=2.1.2,!=2.1.6,>=2.0.1 in /usr/local/lib/python3.7/dist-packages (from matplotlib>=3.2.0->pandas_profiling==2.9.0) (3.0.9)
Requirement already satisfied: kiwisolver>=1.0.1 in /usr/local/lib/python3.7/dist-packages (from matplotlib>=3.2.0->pandas_profiling==2.9.0) (1.4.3)
Requirement already satisfied: typing-extensions in /usr/local/lib/python3.7/dist-packages (from kiwisolver>=1.0.1->matplotlib>=3.2.0->pandas_profiling==2.9.0) (4.1.1)
Requirement already satisfied: fastjsonschema in /usr/local/lib/python3.7/dist-packages (from nbformat>=4.2.0->ipywidgets>=7.5.1->pandas_profiling==2.9.0) (2.15.3)
Requirement already satisfied: jsonschema>=2.6 in /usr/local/lib/python3.7/dist-packages (from nbformat>=4.2.0->ipywidgets>=7.5.1->pandas_profiling==2.9.0) (4.3.3)
Requirement already satisfied: jupyter-core in /usr/local/lib/python3.7/dist-packages (from nbformat>=4.2.0->ipywidgets>=7.5.1->pandas_profiling==2.9.0) (4.10.0)
Requirement already satisfied: pyrsistent!=0.17.0,!=0.17.1,!=0.17.2,>=0.14.0 in /usr/local/lib/python3.7/dist-packages (from jsonschema>=2.6->nbformat>=4.2.0->ipywidgets>=7.5.1->pandas_profiling==2.9.0) (0.18.1)
Requirement already satisfied: importlib-resources>=1.4.0 in /usr/local/lib/python3.7/dist-packages (from jsonschema>=2.6->nbformat>=4.2.0->ipywidgets>=7.5.1->pandas_profiling==2.9.0) (5.7.1)
Requirement already satisfied: importlib-metadata in /usr/local/lib/python3.7/dist-packages (from jsonschema>=2.6->nbformat>=4.2.0->ipywidgets>=7.5.1->pandas_profiling==2.9.0) (4.11.4)
Requirement already satisfied: zipp>=3.1.0 in /usr/local/lib/python3.7/dist-packages (from importlib-resources>=1.4.0->jsonschema>=2.6->nbformat>=4.2.0->ipywidgets>=7.5.1->pandas_profiling==2.9.0) (3.8.0)
Requirement already satisfied: pytz>=2017.3 in /usr/local/lib/python3.7/dist-packages (from pandas!=1.0.0,!=1.0.1,!=1.0.2,!=1.1.0,>=0.25.3->pandas_profiling==2.9.0) (2022.1)
Collecting scipy>=1.4.1
  Downloading scipy-1.7.3-cp37-cp37m-manylinux_2_12_x86_64.manylinux2010_x86_64.whl (38.1 MB)
     |████████████████████████████████| 38.1 MB 1.1 MB/s
Requirement already satisfied: wcwidth in /usr/local/lib/python3.7/dist-packages (from prompt-toolkit<2.0.0,>=1.0.4->ipython>=4.0.0->ipywidgets>=7.5.1->pandas_profiling==2.9.0) (0.2.5)
Requirement already satisfied: six>=1.9.0 in /usr/local/lib/python3.7/dist-packages (from prompt-toolkit<2.0.0,>=1.0.4->ipython>=4.0.0->ipywidgets>=7.5.1->pandas_profiling==2.9.0) (1.15.0)
Requirement already satisfied: chardet<4,>=3.0.2 in /usr/local/lib/python3.7/dist-packages (from requests>=2.23.0->pandas_profiling==2.9.0) (3.0.4)
Requirement already satisfied: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in /usr/local/lib/python3.7/dist-packages (from requests>=2.23.0->pandas_profiling==2.9.0) (1.24.3)
Requirement already satisfied: idna<3,>=2.5 in /usr/local/lib/python3.7/dist-packages (from requests>=2.23.0->pandas_profiling==2.9.0) (2.10)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.7/dist-packages (from requests>=2.23.0->pandas_profiling==2.9.0) (2022.6.15)
Requirement already satisfied: notebook>=4.4.1 in /usr/local/lib/python3.7/dist-packages (from widgetsnbextension~=3.6.0->ipywidgets>=7.5.1->pandas_profiling==2.9.0) (5.3.1)
Requirement already satisfied: terminado>=0.8.1 in /usr/local/lib/python3.7/dist-packages (from notebook>=4.4.1->widgetsnbextension~=3.6.0->ipywidgets>=7.5.1->pandas_profiling==2.9.0) (0.13.3)
Requirement already satisfied: nbconvert in /usr/local/lib/python3.7/dist-packages (from notebook>=4.4.1->widgetsnbextension~=3.6.0->ipywidgets>=7.5.1->pandas_profiling==2.9.0) (5.6.1)
Requirement already satisfied: Send2Trash in /usr/local/lib/python3.7/dist-packages (from notebook>=4.4.1->widgetsnbextension~=3.6.0->ipywidgets>=7.5.1->pandas_profiling==2.9.0) (1.8.0)
Requirement already satisfied: pyzmq>=13 in /usr/local/lib/python3.7/dist-packages (from jupyter-client->ipykernel>=4.5.1->ipywidgets>=7.5.1->pandas_profiling==2.9.0) (23.1.0)
Requirement already satisfied: ptyprocess in /usr/local/lib/python3.7/dist-packages (from terminado>=0.8.1->notebook>=4.4.1->widgetsnbextension~=3.6.0->ipywidgets>=7.5.1->pandas_profiling==2.9.0) (0.7.0)
Requirement already satisfied: PyWavelets in /usr/local/lib/python3.7/dist-packages (from imagehash->visions[type_image_path]==0.5.0->pandas_profiling==2.9.0) (1.3.0)
Requirement already satisfied: defusedxml in /usr/local/lib/python3.7/dist-packages (from nbconvert->notebook>=4.4.1->widgetsnbextension~=3.6.0->ipywidgets>=7.5.1->pandas_profiling==2.9.0) (0.7.1)
Requirement already satisfied: bleach in /usr/local/lib/python3.7/dist-packages (from nbconvert->notebook>=4.4.1->widgetsnbextension~=3.6.0->ipywidgets>=7.5.1->pandas_profiling==2.9.0) (5.0.0)
Requirement already satisfied: entrypoints>=0.2.2 in /usr/local/lib/python3.7/dist-packages (from nbconvert->notebook>=4.4.1->widgetsnbextension~=3.6.0->ipywidgets>=7.5.1->pandas_profiling==2.9.0) (0.4)
Requirement already satisfied: pandocfilters>=1.4.1 in /usr/local/lib/python3.7/dist-packages (from nbconvert->notebook>=4.4.1->widgetsnbextension~=3.6.0->ipywidgets>=7.5.1->pandas_profiling==2.9.0) (1.5.0)
Requirement already satisfied: mistune<2,>=0.8.1 in /usr/local/lib/python3.7/dist-packages (from nbconvert->notebook>=4.4.1->widgetsnbextension~=3.6.0->ipywidgets>=7.5.1->pandas_profiling==2.9.0) (0.8.4)
Requirement already satisfied: testpath in /usr/local/lib/python3.7/dist-packages (from nbconvert->notebook>=4.4.1->widgetsnbextension~=3.6.0->ipywidgets>=7.5.1->pandas_profiling==2.9.0) (0.6.0)
Requirement already satisfied: webencodings in /usr/local/lib/python3.7/dist-packages (from bleach->nbconvert->notebook>=4.4.1->widgetsnbextension~=3.6.0->ipywidgets>=7.5.1->pandas_profiling==2.9.0) (0.5.1)
Building wheels for collected packages: htmlmin, imagehash
  Building wheel for htmlmin (setup.py) ... done
  Created wheel for htmlmin: filename=htmlmin-0.1.12-py3-none-any.whl size=27098 sha256=a5b3ac36478baffccdeea760a472c5b6cc9c934a7f2d4c92a56f00eb8aeb4b5a
  Stored in directory: /root/.cache/pip/wheels/70/e1/52/5b14d250ba868768823940c3229e9950d201a26d0bd3ee8655
  Building wheel for imagehash (setup.py) ... done
  Created wheel for imagehash: filename=ImageHash-4.2.1-py2.py3-none-any.whl size=295206 sha256=64eafbac6a0d8267775628fccb25073b337b95950083956a6bddec3cbbaaf92a
  Stored in directory: /root/.cache/pip/wheels/4c/d5/59/5e3e297533ddb09407769762985d134135064c6831e29a914e
Successfully built htmlmin imagehash
Installing collected packages: tangled-up-in-unicode, scipy, visions, imagehash, phik, htmlmin, confuse, pandas-profiling
  Attempting uninstall: scipy
    Found existing installation: scipy 1.4.1
    Uninstalling scipy-1.4.1:
      Successfully uninstalled scipy-1.4.1
  Attempting uninstall: pandas-profiling
    Found existing installation: pandas-profiling 1.4.1
    Uninstalling pandas-profiling-1.4.1:
      Successfully uninstalled pandas-profiling-1.4.1
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
albumentations 0.1.12 requires imgaug<0.2.7,>=0.2.5, but you have imgaug 0.2.9 which is incompatible.
Successfully installed confuse-1.7.0 htmlmin-0.1.12 imagehash-4.2.1 pandas-profiling-2.9.0 phik-0.12.2 scipy-1.7.3 tangled-up-in-unicode-0.2.0 visions-0.5.0
Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Collecting vision
  Downloading vision-1.0.0.tar.gz (1.6 kB)
Building wheels for collected packages: vision
  Building wheel for vision (setup.py) ... done
  Created wheel for vision: filename=vision-1.0.0-py3-none-any.whl size=2169 sha256=449504409fb380b7cc9b662f4055a8e90e9881357a0dcce745a5bad6e54ddf94
  Stored in directory: /root/.cache/pip/wheels/73/24/1b/ba0312d8c96b9b29673f20076f87bd668d520b05aeb728444e
Successfully built vision
Installing collected packages: vision
Successfully installed vision-1.0.0
Error processing line 1 of /usr/local/lib/python3.7/dist-packages/vision-1.0.0-py3.7-nspkg.pth:

  Traceback (most recent call last):
    File "/usr/lib/python3.7/site.py", line 174, in addpackage
      exec(line)
    File "<string>", line 1, in <module>
    File "<frozen importlib._bootstrap>", line 580, in module_from_spec
  AttributeError: 'NoneType' object has no attribute 'loader'

Remainder of file ignored
Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Collecting pandas==1.2.1
  Downloading pandas-1.2.1-cp37-cp37m-manylinux1_x86_64.whl (9.9 MB)
     |████████████████████████████████| 9.9 MB 4.6 MB/s
Requirement already satisfied: pytz>=2017.3 in /usr/local/lib/python3.7/dist-packages (from pandas==1.2.1) (2022.1)
Requirement already satisfied: python-dateutil>=2.7.3 in /usr/local/lib/python3.7/dist-packages (from pandas==1.2.1) (2.8.2)
Requirement already satisfied: numpy>=1.16.5 in /usr/local/lib/python3.7/dist-packages (from pandas==1.2.1) (1.21.6)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.7/dist-packages (from python-dateutil>=2.7.3->pandas==1.2.1) (1.15.0)
Installing collected packages: pandas
  Attempting uninstall: pandas
    Found existing installation: pandas 1.3.5
    Uninstalling pandas-1.3.5:
      Successfully uninstalled pandas-1.3.5
Successfully installed pandas-1.2.1

In [ ]:
url = "https://drive.google.com/file/d/1KjrSid8AfVggkCX3pmcpRE-OAi8CHVUr/view?usp=sharing"
url2 = "https://drive.google.com/uc?id=" + url.split('/')[-2]
df = pd.read_csv(url2, encoding = "latin-1")
df

,City[a],Country,UN 2018 population estimates[b],City proper[c] Definition,City proper[c] Population,City proper[c] Area (km2),City proper[c] Density (/km2),Metropolitan area[d] Population,Metropolitan area[d] Area (km2),Metropolitan area[d] Density (/km2),Urban area[12] Population,Urban area[12] Area (km2),Urban area[12] Density (/km2)
0,Tokyo,Japan,37400068,Metropolis prefecture,13515271.0,2191.0,6169.0,37274000.0,13452.0,2771.0,39105000.0,8231.0,4751.0
1,Delhi,India,28514000,Capital City,16753235.0,1484.0,11289.0,29000000.0,3483.0,8326.0,31870000.0,2233.0,14272.0
2,Seoul,South Korea,25674800,Special city,10013781.0,605.0,16208.0,25514000.0,11704.0,2180.0,22394000.0,2769.0,8087.0
3,Shanghai,China,25582000,Municipality,24870895.0,6341.0,3922.0,NaN,NaN,NaN,22118000.0,4069.0,5436.0
4,São Paulo,Brazil,21650000,Municipality,12252023.0,1521.0,8055.0,21734682.0,7947.0,2735.0,22495000.0,3237.0,6949.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
76,"Washington, D.C.",United States,5207000,Federal district,702455.0,177.0,3969.0,6263245.0,17009.0,368.0,7583000.0,5501.0,1378.0
77,Yangon,Myanmar,5157000,City,NaN,NaN,NaN,NaN,NaN,NaN,6497000.0,603.0,10774.0
78,Alexandria,Egypt,5086000,Urban governorate,NaN,NaN,NaN,NaN,NaN,NaN,4857000.0,293.0,16577.0
79,Jinan,China,5052000,City (sub - provincial),8700000.0,10244.0,849.0,NaN,NaN,NaN,4381000.0,798.0,5490.0
80,Guadalajara,Mexico,5023000,Municipality,1385621.0,151.0,9176.0,5286642.0,3560.0,1485.0,5437000.0,313.0,17371.0

In [ ]:
prof = ProfileReport(df)
prof.to_file('report.html')
files.download('report.html')

Summarize dataset:   0%|          | 0/27 [00:00<?, ?it/s]

Generate report structure:   0%|          | 0/1 [00:00<?, ?it/s]

Render HTML:   0%|          | 0/1 [00:00<?, ?it/s]

Export report to file:   0%|          | 0/1 [00:00<?, ?it/s]

## **Text Classification**

In [ ]:
import pandas as pd
import numpy as np
import spacy
from textblob import TextBlob
from sklearn.metrics import classification_report

In [ ]:
data = pd.read_excel("/content/drive/MyDrive/TDS/data/TextBlobData.xlsx")
data.head()

                                              review
0  i think it`s under a honeymoon by the good lif...
1  Ahhh i`m sqeaky clean and fresh. Even though i...
2  Why kiss the feet of the people who kick you w...
3  you know you want to come keep me company whil...
4  it was hours ago i came in.... and it`s only n...

In [ ]:
data['TextBlob_Subjectivity'] = data['review'].apply(lambda x: TextBlob(x).sentiment.subjectivity)
data['TextBlob_Polarity'] = data['review'].apply(lambda x: TextBlob(x).sentiment.polarity)

In [ ]:
data['TextBlob_Analysis'] = data['TextBlob_Polarity'].apply(lambda x: 'negative' if x<0 else 'positive')

In [ ]:
data[['TextBlob_Subjectivity', 'TextBlob_Polarity', 'TextBlob_Analysis']]

   TextBlob_Subjectivity  TextBlob_Polarity TextBlob_Analysis
0               0.600000           0.700000          positive
1               0.611111           0.191667          positive
2               0.300000           1.000000          positive
3               0.750000           0.375000          positive
4               1.000000           0.000000          positive

In [ ]:
data

,review,TextBlob_Subjectivity,TextBlob_Polarity,TextBlob_Analysis
0,i think it`s under a honeymoon by the good lif...,0.600000,0.700000,positive
1,Ahhh i`m sqeaky clean and fresh. Even though i...,0.611111,0.191667,positive
2,Why kiss the feet of the people who kick you w...,0.300000,1.000000,positive
3,you know you want to come keep me company whil...,0.750000,0.375000,positive
4,it was hours ago i came in.... and it`s only n...,1.000000,0.000000,positive

In [ ]:
print(classification_report(data['sentiment'], data['TextBlob_Analysis']))

              precision    recall  f1-score   support

    negative       0.88      0.46      0.60       499
    positive       0.64      0.94      0.76       501

    accuracy                           0.70      1000
   macro avg       0.76      0.70      0.68      1000
weighted avg       0.76      0.70      0.68      1000

# **Geospatial Analysis**

In [ ]:
import pandas as pd
import numpy as np
import folium
import geopy.distance

In [ ]:
data = pd.read_csv('https://drive.google.com/uc?id=19JERBe0ndadkMPKDFZ0rTEZqdI50zDfk')
data.head(10)

         lat        lng      store                                 address
0  40.711000 -74.000878  Starbucks        375 Pearl st, New York, NY 10038
1  40.707142 -74.004987  Starbucks     135 John Street, New York, NY 10038
2  40.708411 -74.007404  Starbucks  100 William Street, New York, NY 10038
3  40.711644 -74.006667  Starbucks     38 Park Row, #4, New York, NY 10038
4  40.710171 -74.007931  Starbucks   130 Fulton Street, New York, NY 10038
5  40.706316 -74.006582  Starbucks      80 Pine Street, New York, NY 10005
6  40.712208 -74.008192  Starbucks        233 Broadway, New York, NY 10279
7  40.708742 -74.009508  Starbucks   55 Liberty Street, New York, NY 10005
8  40.706033 -74.008348  Starbucks          60 Wall St, New York, NY 10005
9  40.704817 -74.007231  Starbucks         99 Wall St., New York, NY 10005

# **KUMU Data Preparation**

In [ ]:
# data link https://www.imdb.com/interfaces/
# title
import numpy as np
import pandas as pd

In [ ]:

!rm *.tsv.gz
!wget -q https://datasets.imdbws.com/name.basics.tsv.gz
!wget -q https://datasets.imdbws.com/title.principals.tsv.gz
!wget -q https://datasets.imdbws.com/title.basics.tsv.gz
!wget -q https://datasets.imdbws.com/title.akas.tsv.gz
!ls -la

rm: cannot remove '*.tsv.gz': No such file or directory
total 1045832
drwxr-xr-x 1 root root      4096 Jul 17 17:07 .
drwxr-xr-x 1 root root      4096 Jul 17 17:02 ..
drwxr-xr-x 4 root root      4096 Jul 13 13:42 .config
-rw-r--r-- 1 root root 230527255 Jul 16 13:24 name.basics.tsv.gz
drwxr-xr-x 1 root root      4096 Jul 13 13:43 sample_data
-rw-r--r-- 1 root root 276990464 Jul 16 13:24 title.akas.tsv.gz
-rw-r--r-- 1 root root 158641925 Jul 16 13:24 title.basics.tsv.gz
-rw-r--r-- 1 root root 404734795 Jul 16 13:24 title.principals.tsv.gz

In [ ]:
name = pd.read_csv('name.basics.tsv.gz', sep = '\t', na_values = '\\N', dtype={'birthYear': float}).set_index('nconst')
name.head()

,primaryName,birthYear,deathYear,primaryProfession,knownForTitles
nconst,,,,,
nm0000001,Fred Astaire,1899.0,1987.0,"soundtrack,actor,miscellaneous","tt0053137,tt0072308,tt0031983,tt0050419"
nm0000002,Lauren Bacall,1924.0,2014.0,"actress,soundtrack","tt0071877,tt0038355,tt0037382,tt0117057"
nm0000003,Brigitte Bardot,1934.0,NaN,"actress,soundtrack,music_department","tt0057345,tt0054452,tt0056404,tt0049189"
nm0000004,John Belushi,1949.0,1982.0,"actor,soundtrack,writer","tt0078723,tt0072562,tt0077975,tt0080455"
nm0000005,Ingmar Bergman,1918.0,2007.0,"writer,director,actor","tt0050986,tt0083922,tt0050976,tt0060827"

# **TDS Project 2**

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
books = pd.read_csv("/content/drive/MyDrive/TDS/data/books.csv")
books

,book_id,goodreads_book_id,best_book_id,work_id,books_count,isbn,isbn13,authors,original_publication_year,original_title,...,work_ratings_count,work_text_reviews_count,ratings_1,ratings_2,ratings_3,ratings_4,ratings_5,image_url,small_image_url,NonEnglish
0,30,8442457,19288043,13306276,196,297859382,9.780298e+12,Gillian Flynn,2012.0,Gone Girl,...,1626519,121614,38874,80807,280331,616031,610476,https://images.gr-assets.com/books/1339602131m...,https://images.gr-assets.com/books/1339602131s...,0
1,331,10916,10916,3349846,76,61150142,9.780061e+12,Jodi Picoult,1998.0,The Pact,...,235359,9257,3586,11789,50494,85430,84060,https://images.gr-assets.com/books/1410754561m...,https://images.gr-assets.com/books/1410754561s...,0
2,342,13497818,13497818,19926990,139,316228532,9.780316e+12,J.K. Rowling,2012.0,The Casual Vacancy,...,254461,28751,24583,38326,74611,75741,41200,https://images.gr-assets.com/books/1358266832m...,https://images.gr-assets.com/books/1358266832s...,0
3,414,6948436,6948436,4126074,82,1416589643,9.781417e+12,Chris Cleave,2008.0,The Other Hand,...,197953,19680,5111,16849,54949,77107,43937,https://images.gr-assets.com/books/1344401905m...,https://images.gr-assets.com/books/1344401905s...,0
4,616,14864,14864,3375925,65,743275012,9.780743e+12,Jodi Picoult,2000.0,Plain Truth,...,138814,6231,1123,5518,32571,57131,42471,https://s.gr-assets.com/assets/nophoto/book/11...,https://s.gr-assets.com/assets/nophoto/book/50...,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
485,9971,12602078,25781538,17617275,8,NaN,NaN,Melody Anne,2011.0,NaN,...,17606,881,395,1182,4378,6060,5591,https://images.gr-assets.com/books/1368675679m...,https://images.gr-assets.com/books/1368675679s...,0
486,9978,162332,162332,880874,70,679750150,9.780680e+12,"Yukio Mishima, John Nathan",1963.0,午後の曳航 [Gogo no eikō],...,10541,755,142,590,2414,4551,2844,https://images.gr-assets.com/books/1327629352m...,https://images.gr-assets.com/books/1327629352s...,0
487,9981,106312,106312,29083,58,739455834,9.780739e+12,Jeffery Deaver,2005.0,The Twelfth Card,...,12134,495,72,390,2874,5155,3643,https://images.gr-assets.com/books/1328407138m...,https://images.gr-assets.com/books/1328407138s...,0
488,9986,183092,183092,176939,16,310257689,9.780310e+12,Terri Blackstock,2006.0,Night Light: A Restoration Novel,...,8862,218,96,172,1115,2658,4821,https://s.gr-assets.com/assets/nophoto/book/11...,https://s.gr-assets.com/assets/nophoto/book/50...,0
489,9987,8087038,8087038,12823536,29,312651198,9.780313e+12,Iris Johansen,2010.0,Chasing The Night,...,10964,411,113,331,2127,3957,4436,https://s.gr-assets.com/assets/nophoto/book/11...,https://s.gr-assets.com/assets/nophoto/book/50...,0

In [ ]:
ratings = pd.read_csv("/content/drive/MyDrive/TDS/data/ratings.csv")
ratings

        user_id  book_id  rating
0            18     1102       2
1            18     8329       4
2            22     8512       2
3            78     8805       3
4            65     8805       5
...         ...      ...     ...
142245    48801     9216       5
142246    34338     7197       4
142247    42326     9674       4
142248    39374      623       3
142249    10596     1786       4

[142250 rows x 3 columns]

In [ ]:
toread = pd.read_csv("/content/drive/MyDrive/TDS/data/toread.csv")
toread

       user_id  book_id
0          149     8382
1          185     8167
2           10     4369
3          162     2938
4          718     3320
...        ...      ...
25518    38965     4461
25519    41259     8242
25520     5237     1551
25521    53358     1028
25522    45870      744

[25523 rows x 2 columns]

In [ ]:
book_tags = pd.read_csv("/content/drive/MyDrive/TDS/data/book_tags.csv")
book_tags

       goodreads_book_id  tag_id  count
0                     29   30574   5492
1                     29    8717    867
2                     29   21689    410
3                     29   15048    170
4                     29   21773    167
...                  ...     ...    ...
48951           31194270   17222      3
48952           31194270   22758      2
48953           31194270   22813      2
48954           31194270   21825      2
48955           31194270    2227      2

[48956 rows x 3 columns]

In [ ]:
len(books.loc[books.original_title != books.title])

278

In [ ]:
books['titleEqual'] = np.where(books['original_title'] != books['title'], 1, 0)
books['titleEqual'].value_counts()

0    212
1    206
Name: titleEqual, dtype: int64

In [ ]:
books.book_id.nunique(dropna = True)

418

In [ ]:
ratings.user_id.nunique(dropna = True)
len(ratings["user_id"].unique())

48379

In [ ]:
rating_count = books['work_ratings_count'].max()
print(rating_count)
books.query('work_ratings_count == '+ str(rating_count))['title']

1878095

0    The Kite Runner
Name: title, dtype: object

In [ ]:
book_tags['tag_id'].value_counts().tail(150)

32064    1
11895    1
638      1
9514     1
16297    1
        ..
22216    1
1206     1
5049     1
788      1
17222    1
Name: tag_id, Length: 150, dtype: int64

In [ ]:
temp_df = book_tags["tag_id"].value_counts()
maxval = temp_df.max()
temp_df = temp_df[temp_df.values == maxval]
temp_df.sort_index(inplace=True)
temp_df.index[0]

24662

In [ ]:
q6_df = book_tags.groupby("goodreads_book_id").agg({"count": "sum"}).reset_index()
max_df = q6_df["count"].max()

goodreads_book_id1 = q6_df[q6_df["count"] == max_df]["goodreads_book_id"]
books[books["goodreads_book_id"] == goodreads_book_id1.values[0]]["title"]

0    Gone Girl
Name: title, dtype: object

In [ ]:
temp_df = toread['book_id'].value_counts()
maxval = temp_df.max()
temp = temp_df[temp_df.values == maxval]
temp_df.sort_index(inplace = True)
temp_df.index[0]

30

In [ ]:
toread['book_id'].value_counts()

342     1521
30       801
1028     768
623      426
1275     285
        ...
9560       2
9971       2
7488       2
8684       2
9248       1
Name: book_id, Length: 489, dtype: int64

In [ ]:
books.query('book_id == '+ str(342))

,book_id,goodreads_book_id,best_book_id,work_id,books_count,isbn,isbn13,authors,original_publication_year,original_title,...,work_ratings_count,work_text_reviews_count,ratings_1,ratings_2,ratings_3,ratings_4,ratings_5,image_url,small_image_url,NonEnglish
2,342,13497818,13497818,19926990,139,316228532,9.780316e+12,J.K. Rowling,2012.0,The Casual Vacancy,...,254461,28751,24583,38326,74611,75741,41200,https://images.gr-assets.com/books/1358266832m...,https://images.gr-assets.com/books/1358266832s...,0

In [ ]:
max_to_read = toread["book_id"].value_counts()
max_book_id = max_to_read.index[0]
books[books["book_id"] == max_book_id]["goodreads_book_id"]

2    13497818
Name: goodreads_book_id, dtype: int64

In [ ]:
temp_df = toread['book_id'].value_counts()
maxval = temp_df.min()
temp = temp_df[temp_df.values == maxval]
temp_df.sort_index(inplace = True)
temp_df.index[0]

30

In [ ]:
books['average_rating'].min()
books[books["average_rating"] == 3.01]['title']

82    Adultery
Name: title, dtype: object

In [ ]:
min_rating = books["average_rating"].min()

books[books["average_rating"] == min_rating]["title"]

82    Adultery
Name: title, dtype: object

In [ ]:
q10_df = book_tags.groupby("goodreads_book_id").agg({"count": "sum"}).reset_index()
min_count = q10_df["count"].min()
goodreads_book_id1 = q10_df[q10_df["count"] == min_count][
    "goodreads_book_id"
]
goodreads_book_id1.sort_index(inplace=True)
print(goodreads_book_id1.values[0])

824318

In [ ]:
book_tags.tag_id.nunique(dropna = True)

5986

In [ ]:
len(book_tags.tag_id.unique())

5986

In [ ]:
books['average_rating'].mean()

3.973795918367347

In [ ]:
books[books['original_publication_year'] == 2000].shape[0]

7

In [ ]:
books["original_title"].isnull().value_counts()

False    418
True      72
Name: original_title, dtype: int64

In [ ]:
from textblob import TextBlob

books = books[~books["original_title"].isna()]
books["TextBlob_Polarity"] = books["title"].apply(
    lambda x: TextBlob(x).sentiment.polarity
)

print("Take the True Value count")
print((books["TextBlob_Polarity"] > 0).value_counts())

Take the True Value count
False    340
True      78
Name: TextBlob_Polarity, dtype: int64

In [ ]:
q15_df = book_tags.groupby("tag_id").agg({"count": "sum"}).reset_index()
q15_df.sort_values(by=["count"], inplace=True, ascending=False)
q15_df = q15_df.head(20)

q15_df.sort_values(by=["count"], inplace=True) # sorting for plotting purpose
# Write to a file

q15_df.to_csv("/content/drive/MyDrive/TDS/data/q15_data.csv") # to be uploaded to flourish

In [ ]:
conditions = [
    (books["average_rating"] < 0.5),
    (books["average_rating"] >= 0.5) & (books["average_rating"] < 1.5),
    (books["average_rating"] >= 1.5) & (books["average_rating"] < 2.5),
    (books["average_rating"] >= 2.5) & (books["average_rating"] < 3.5),
    (books["average_rating"] >= 3.5) & (books["average_rating"] < 4.5),
    (books["average_rating"] >= 4.5) & (books["average_rating"] < 5.5),
]

# create a list of the values we want to assign for each condition
values = [0, 1, 2, 3, 4, 5]

books["bucket"] = np.select(conditions, values)


q16_df = books["bucket"].value_counts()
q16_df = q16_df.reset_index()

q16_df.rename(columns={"index": "Bucket", "bucket": "Count"}, inplace=True)


print(q16_df)


# *************If you are missing any buckets add them manullay Comment/Uncommnet the below code***************


missing_df = pd.DataFrame({'Bucket':[0,1,2],'Count':[0,0,0]}) # Add missing buckets
q16_df = pd.concat([q16_df,missing_df])

q16_df.sort_values(by=['Bucket'])


# Sorting by bucket
q16_df.sort_values(by=["Bucket"], inplace=True)


# write to a csv file , upload it to flourish

q16_df.to_csv("/content/drive/MyDrive/TDS/data/q16_data.csv")

   Bucket  Count
0       4    399
1       3     12
2       5      7